// Predefined Master Product Catalog Dataset for VENDORFLOW
// Covers IT Hardware, Electronics, Office Equipment, Furniture, Industrial Equipment, Stationery, Safety Equipment, Software
// All prices in INR. All data based on publicly available manufacturer/retailer specifications.

const masterCatalogProducts = [
  // ==========================================
  // ELECTRONICS - SMARTPHONES
  // ==========================================
  {
    catalogId: 'MASTER-APPL-IP15-128',
    productName: 'Apple iPhone 15 (128GB)',
    brand: 'Apple',
    model: 'iPhone 15',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 69900,
    currency: 'INR',
    description: 'Dynamic Island, 48MP main camera with 2x Telephoto, USB-C, durable color-infused glass and aluminum design.',
    specifications: 'Display: 6.1" Super Retina XDR OLED | Chip: A16 Bionic | Storage: 128GB | Camera: 48MP Dual Camera | Charging: USB-C | OS: iOS 17',
    specificationsObject: {
      'Display': '6.1-inch Super Retina XDR OLED (2556 x 1179)',
      'Chipset': 'Apple A16 Bionic (4nm)',
      'Storage': '128 GB NVMe',
      'Rear Camera': '48 MP Main + 12 MP Ultra Wide',
      'Front Camera': '12 MP TrueDepth',
      'Connector': 'USB-C',
      'Battery': 'Up to 20 hours video playback',
      'Water Resistance': 'IP68 (6m up to 30 mins)',
      'OS': 'iOS 17',
      'Warranty': '1 Year Apple Limited Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black - 128GB', color: 'Black', storage: '128GB', referencePrice: 69900, sku: 'IP15-128-BLK' },
      { name: 'Blue - 128GB', color: 'Blue', storage: '128GB', referencePrice: 69900, sku: 'IP15-128-BLU' },
      { name: 'Pink - 128GB', color: 'Pink', storage: '128GB', referencePrice: 69900, sku: 'IP15-128-PNK' },
      { name: 'Green - 128GB', color: 'Green', storage: '128GB', referencePrice: 69900, sku: 'IP15-128-GRN' },
      { name: 'Yellow - 128GB', color: 'Yellow', storage: '128GB', referencePrice: 69900, sku: 'IP15-128-YLW' },
    ],
    tags: ['apple', 'iphone', 'iphone 15', 'smartphone', 'mobile', 'ios'],
  },
  {
    catalogId: 'MASTER-APPL-IP15-256',
    productName: 'Apple iPhone 15 (256GB)',
    brand: 'Apple',
    model: 'iPhone 15',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 79900,
    currency: 'INR',
    description: 'Dynamic Island, 48MP main camera with 2x Telephoto, USB-C, 256GB onboard storage.',
    specifications: 'Display: 6.1" Super Retina XDR OLED | Chip: A16 Bionic | Storage: 256GB | Camera: 48MP Dual Camera | Charging: USB-C',
    specificationsObject: {
      'Display': '6.1-inch Super Retina XDR OLED',
      'Chipset': 'Apple A16 Bionic',
      'Storage': '256 GB NVMe',
      'Rear Camera': '48 MP Main + 12 MP Ultra Wide',
      'Front Camera': '12 MP TrueDepth',
      'Connector': 'USB-C',
      'OS': 'iOS 17',
      'Warranty': '1 Year Apple Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black - 256GB', color: 'Black', storage: '256GB', referencePrice: 79900, sku: 'IP15-256-BLK' },
      { name: 'Blue - 256GB', color: 'Blue', storage: '256GB', referencePrice: 79900, sku: 'IP15-256-BLU' },
      { name: 'Pink - 256GB', color: 'Pink', storage: '256GB', referencePrice: 79900, sku: 'IP15-256-PNK' },
      { name: 'Green - 256GB', color: 'Green', storage: '256GB', referencePrice: 79900, sku: 'IP15-256-GRN' },
    ],
    tags: ['apple', 'iphone', 'iphone 15', 'smartphone', 'mobile', '256gb'],
  },
  {
    catalogId: 'MASTER-APPL-IP15-512',
    productName: 'Apple iPhone 15 (512GB)',
    brand: 'Apple',
    model: 'iPhone 15',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 99900,
    currency: 'INR',
    description: 'Apple iPhone 15 with 512GB storage, 48MP camera system, USB-C connectivity, and A16 Bionic chip.',
    specifications: 'Display: 6.1" Super Retina XDR OLED | Chip: A16 Bionic | Storage: 512GB | Camera: 48MP | Charging: USB-C',
    specificationsObject: {
      'Display': '6.1-inch Super Retina XDR OLED',
      'Chipset': 'Apple A16 Bionic',
      'Storage': '512 GB NVMe',
      'Rear Camera': '48 MP Main + 12 MP Ultra Wide',
      'Front Camera': '12 MP TrueDepth',
      'Connector': 'USB-C',
      'OS': 'iOS 17',
      'Warranty': '1 Year Apple Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black - 512GB', color: 'Black', storage: '512GB', referencePrice: 99900, sku: 'IP15-512-BLK' },
      { name: 'Blue - 512GB', color: 'Blue', storage: '512GB', referencePrice: 99900, sku: 'IP15-512-BLU' },
      { name: 'Pink - 512GB', color: 'Pink', storage: '512GB', referencePrice: 99900, sku: 'IP15-512-PNK' },
    ],
    tags: ['apple', 'iphone', 'iphone 15', 'smartphone', 'mobile', '512gb'],
  },
  {
    catalogId: 'MASTER-APPL-IP15PRO-256',
    productName: 'Apple iPhone 15 Pro (256GB)',
    brand: 'Apple',
    model: 'iPhone 15 Pro',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 134900,
    currency: 'INR',
    description: 'Titanium design, A17 Pro chip, 48MP Main + 12MP Ultra Wide + 12MP 3x Telephoto, USB-C with USB 3 speeds.',
    specifications: 'Display: 6.1" Super Retina XDR ProMotion OLED | Chip: A17 Pro | Storage: 256GB | Camera: 48MP Triple Rear | Connectivity: USB-C (USB 3)',
    specificationsObject: {
      'Display': '6.1-inch Super Retina XDR OLED with ProMotion (1-120Hz)',
      'Chipset': 'Apple A17 Pro (3nm)',
      'Storage': '256 GB NVMe',
      'Rear Camera': '48 MP Main + 12 MP Ultra Wide + 12 MP 3x Telephoto',
      'Front Camera': '12 MP TrueDepth',
      'Connector': 'USB-C (USB 3 speeds)',
      'Battery': 'Up to 23 hours video playback',
      'Build': 'Grade 5 Titanium frame, Textured matte glass back',
      'OS': 'iOS 17',
      'Warranty': '1 Year Apple Limited Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black Titanium - 256GB', color: 'Black Titanium', storage: '256GB', referencePrice: 134900, sku: 'IP15PRO-256-BLK' },
      { name: 'White Titanium - 256GB', color: 'White Titanium', storage: '256GB', referencePrice: 134900, sku: 'IP15PRO-256-WHT' },
      { name: 'Blue Titanium - 256GB', color: 'Blue Titanium', storage: '256GB', referencePrice: 134900, sku: 'IP15PRO-256-BLU' },
      { name: 'Natural Titanium - 256GB', color: 'Natural Titanium', storage: '256GB', referencePrice: 134900, sku: 'IP15PRO-256-NAT' },
    ],
    tags: ['apple', 'iphone', 'iphone 15 pro', 'smartphone', 'pro', 'titanium'],
  },
  {
    catalogId: 'MASTER-SMSG-S24-256',
    productName: 'Samsung Galaxy S24 5G (8GB RAM, 256GB)',
    brand: 'Samsung',
    model: 'Galaxy S24',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 74999,
    currency: 'INR',
    description: 'Flagship Galaxy AI phone with 6.2-inch Dynamic AMOLED 2X 120Hz display and triple rear camera.',
    specifications: 'Display: 6.2" Dynamic AMOLED 2X 120Hz | RAM: 8GB | Storage: 256GB | Camera: 50MP OIS Triple Camera | Battery: 4000mAh',
    specificationsObject: {
      'Display': '6.2-inch FHD+ Dynamic AMOLED 2X, 1-120Hz',
      'Processor': 'Exynos 2400 Deca-Core / Snapdragon 8 Gen 3',
      'RAM': '8 GB LPDDR5X',
      'Storage': '256 GB UFS 4.0',
      'Camera': '50MP (Wide) + 10MP (Telephoto 3x) + 12MP (Ultra-Wide)',
      'Battery': '4,000 mAh with 25W fast charge',
      'Network': '5G',
      'Warranty': '1 Year Manufacturer Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Onyx Black', color: 'Onyx Black', storage: '256GB', ram: '8GB', referencePrice: 74999, sku: 'S24-BLK' },
      { name: 'Marble Gray', color: 'Marble Gray', storage: '256GB', ram: '8GB', referencePrice: 74999, sku: 'S24-GRY' },
      { name: 'Cobalt Violet', color: 'Cobalt Violet', storage: '256GB', ram: '8GB', referencePrice: 74999, sku: 'S24-VLT' },
    ],
    tags: ['samsung', 'galaxy', 's24', 'android', 'smartphone', '5g'],
  },
  {
    catalogId: 'MASTER-SMSG-S24U-256',
    productName: 'Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB)',
    brand: 'Samsung',
    model: 'Galaxy S24 Ultra',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 134999,
    currency: 'INR',
    description: 'Galaxy AI flagship with built-in S Pen, 200MP camera, titanium frame, and 5000mAh battery.',
    specifications: 'Display: 6.8" QHD+ Dynamic AMOLED 2X | RAM: 12GB | Storage: 256GB | Camera: 200MP + 50MP + 10MP + 12MP | Battery: 5000mAh | S Pen included',
    specificationsObject: {
      'Display': '6.8-inch QHD+ Dynamic AMOLED 2X, 1-120Hz',
      'Processor': 'Snapdragon 8 Gen 3 for Galaxy',
      'RAM': '12 GB LPDDR5X',
      'Storage': '256 GB UFS 4.0',
      'Camera': '200MP (Wide) + 50MP (Telephoto 5x) + 10MP (Telephoto 3x) + 12MP (Ultra Wide)',
      'Battery': '5,000 mAh with 45W fast charge',
      'Stylus': 'Built-in S Pen',
      'Network': '5G',
      'Warranty': '1 Year Manufacturer Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Titanium Black - 256GB', color: 'Titanium Black', storage: '256GB', ram: '12GB', referencePrice: 134999, sku: 'S24U-BLK' },
      { name: 'Titanium Gray - 256GB', color: 'Titanium Gray', storage: '256GB', ram: '12GB', referencePrice: 134999, sku: 'S24U-GRY' },
    ],
    tags: ['samsung', 'galaxy s24 ultra', 's pen', 'smartphone', '5g', '200mp'],
  },
  {
    catalogId: 'MASTER-OP-12-256',
    productName: 'OnePlus 12 5G (12GB RAM, 256GB)',
    brand: 'OnePlus',
    model: 'OnePlus 12',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 64999,
    currency: 'INR',
    description: 'Flagship killer with Snapdragon 8 Gen 3, Hasselblad triple camera, 100W SUPERVOOC charging, and 50W wireless charging.',
    specifications: 'Display: 6.82" QHD+ LTPO AMOLED 120Hz | RAM: 12GB | Storage: 256GB | Camera: 50MP Hasselblad Triple | Battery: 5400mAh | Charge: 100W',
    specificationsObject: {
      'Display': '6.82-inch QHD+ LTPO 4.0 AMOLED, 1-120Hz',
      'Processor': 'Snapdragon 8 Gen 3 Octa-Core',
      'RAM': '12 GB LPDDR5X',
      'Storage': '256 GB UFS 4.0',
      'Camera': '50MP (OIS) + 48MP (Ultra-Wide) + 64MP (Periscope 3x)',
      'Battery': '5,400 mAh with 100W SUPERVOOC + 50W AirVOOC',
      'Network': '5G',
      'Warranty': '1 Year Brand Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1581993192873-05e8c2aad57e?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Silky Black - 12GB/256GB', color: 'Silky Black', storage: '256GB', ram: '12GB', referencePrice: 64999, sku: 'OP12-256-BLK' },
      { name: 'Flowy Emerald - 12GB/256GB', color: 'Flowy Emerald', storage: '256GB', ram: '12GB', referencePrice: 64999, sku: 'OP12-256-GRN' },
    ],
    tags: ['oneplus', 'oneplus 12', 'snapdragon', 'smartphone', '5g', 'hasselblad'],
  },

  // ==========================================
  // ELECTRONICS - TABLETS
  // ==========================================
  {
    catalogId: 'MASTER-APPL-IPAD-AIR-M2-256',
    productName: 'Apple iPad Air M2 11-inch (256GB Wi-Fi)',
    brand: 'Apple',
    model: 'iPad Air M2 11"',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 89900,
    currency: 'INR',
    description: 'Apple M2 chip, 11-inch Liquid Retina display, USB-C with 10Gbps data transfer, 12MP Ultra Wide front camera, landscape orientation.',
    specifications: 'Display: 11" Liquid Retina | Chip: Apple M2 | Storage: 256GB | Camera: 12MP Rear + 12MP Ultra Wide Front | Connectivity: Wi-Fi 6E, Bluetooth 5.3',
    specificationsObject: {
      'Display': '11-inch Liquid Retina (2360x1640, 264 ppi)',
      'Chip': 'Apple M2 (8-core CPU, 10-core GPU)',
      'Storage': '256 GB',
      'Front Camera': '12 MP Ultra Wide (landscape)',
      'Rear Camera': '12 MP Wide with Smart HDR 4',
      'Connectivity': 'Wi-Fi 6E (802.11ax), Bluetooth 5.3, USB-C (USB 3)',
      'Battery': 'Up to 10 hours',
      'Stylus': 'Apple Pencil Pro / USB-C compatible (sold separately)',
      'Warranty': '1 Year Apple Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Blue - 256GB Wi-Fi', color: 'Blue', storage: '256GB', referencePrice: 89900, sku: 'IPADAIRM2-256-BLU' },
      { name: 'Purple - 256GB Wi-Fi', color: 'Purple', storage: '256GB', referencePrice: 89900, sku: 'IPADAIRM2-256-PUR' },
      { name: 'Starlight - 256GB Wi-Fi', color: 'Starlight', storage: '256GB', referencePrice: 89900, sku: 'IPADAIRM2-256-SLT' },
    ],
    tags: ['apple', 'ipad', 'ipad air', 'm2', 'tablet'],
  },
  {
    catalogId: 'MASTER-SMSG-TAB-S9FE-128',
    productName: 'Samsung Galaxy Tab S9 FE (6GB RAM, 128GB)',
    brand: 'Samsung',
    model: 'Galaxy Tab S9 FE',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 32999,
    currency: 'INR',
    description: '10.9-inch FHD AMOLED display, Exynos 1380 processor, S Pen included, IP68 water/dust resistance.',
    specifications: 'Display: 10.9" FHD+ AMOLED | RAM: 6GB | Storage: 128GB | Battery: 10090mAh | S Pen included | IP68 rated',
    specificationsObject: {
      'Display': '10.9-inch FHD+ (2304x1440) TFT LCD',
      'Processor': 'Samsung Exynos 1380 Octa-Core',
      'RAM': '6 GB',
      'Storage': '128 GB + microSD expandable',
      'Camera': '8 MP Rear + 10 MP Front',
      'Battery': '10,090 mAh with 45W wired charging',
      'Stylus': 'S Pen included',
      'Rating': 'IP68 Water and Dust Resistant',
      'Warranty': '1 Year Manufacturer Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Gray - 6GB/128GB', color: 'Gray', storage: '128GB', ram: '6GB', referencePrice: 32999, sku: 'TABS9FE-128-GRY' },
      { name: 'Mint - 6GB/128GB', color: 'Mint', storage: '128GB', ram: '6GB', referencePrice: 32999, sku: 'TABS9FE-128-MNT' },
      { name: 'Lavender - 6GB/128GB', color: 'Lavender', storage: '128GB', ram: '6GB', referencePrice: 32999, sku: 'TABS9FE-128-LAV' },
    ],
    tags: ['samsung', 'galaxy tab', 'tablet', 'android', 's pen'],
  },

  // ==========================================
  // ELECTRONICS - AUDIO & ACCESSORIES
  // ==========================================
  {
    catalogId: 'MASTER-SONY-WH1000XM5',
    productName: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    brand: 'Sony',
    model: 'WH-1000XM5',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 29990,
    currency: 'INR',
    description: 'Industry-leading noise canceling with two processors and 8 microphones, LDAC Hi-Res Audio, 30-hour battery life.',
    specifications: 'Battery Life: 30 hours | Noise Cancelling: Auto NC Optimizer | Weight: 250g | Connectivity: Bluetooth 5.2, Multipoint, 3.5mm Aux',
    specificationsObject: {
      'Headphone Type': 'Over-Ear, Closed Dynamic',
      'Driver Unit': '30 mm Carbon Fiber composite',
      'Battery Life': 'Up to 30 hours (NC ON), 40 hours (NC OFF)',
      'Charging Time': 'Approx. 3.5 hrs (3 min charge gives 3 hrs playback)',
      'Microphones': '8 microphones with beamforming',
      'Connectivity': 'Bluetooth 5.2, NFC, 3.5mm aux',
      'Weight': '250 g',
      'Warranty': '1 Year Brand Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 29990, sku: 'WH1000XM5-B' },
      { name: 'Silver', color: 'Silver', referencePrice: 29990, sku: 'WH1000XM5-S' },
    ],
    tags: ['sony', 'headphones', 'noise cancelling', 'bluetooth', 'audio'],
  },
  {
    catalogId: 'MASTER-SONY-WFSP800N',
    productName: 'Sony WF-SP800N Wireless In-Ear Earbuds with Noise Cancellation',
    brand: 'Sony',
    model: 'WF-SP800N',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 9990,
    currency: 'INR',
    description: 'Truly wireless sport earbuds with active noise cancellation, IPX5 water resistance, and up to 18 hours total battery.',
    specifications: 'Driver: 9mm | ANC: Dual Noise Sensor | Battery: 9h earbuds + 9h case = 18h total | Water: IPX5 | Connectivity: Bluetooth 5.0',
    specificationsObject: {
      'Driver': '9mm diameter, dome type',
      'Active Noise Cancellation': 'Yes (Dual Noise Sensor Technology)',
      'Battery (Earbuds)': 'Up to 9 hours (ANC on)',
      'Battery (Total with Case)': 'Up to 18 hours',
      'Water Resistance': 'IPX5',
      'Connectivity': 'Bluetooth 5.0',
      'Weight': '9.8 g per earbud',
      'Warranty': '1 Year Brand Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 9990, sku: 'WFSP800N-BLK' },
      { name: 'Blue', color: 'Blue', referencePrice: 9990, sku: 'WFSP800N-BLU' },
    ],
    tags: ['sony', 'earbuds', 'tws', 'noise cancelling', 'wireless earbuds'],
  },
  {
    catalogId: 'MASTER-LOGI-MXM3S',
    productName: 'Logitech MX Master 3S Performance Wireless Mouse',
    brand: 'Logitech',
    model: 'MX Master 3S',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 9495,
    currency: 'INR',
    description: 'Quiet Click ergonomic wireless mouse with 8000 DPI track-on-glass sensor and MagSpeed electromagnetic scrolling.',
    specifications: 'Sensor: 8,000 DPI Darkfield | Buttons: 7 buttons | Battery: Up to 70 days rechargeable | Connectivity: Logi Bolt USB, Bluetooth',
    specificationsObject: {
      'DPI Range': '200 to 8000 DPI',
      'Scroll Wheel': 'MagSpeed electromagnetic with Smartshift',
      'Battery': '500 mAh Li-Po rechargeable (USB-C)',
      'Connectivity': 'Bluetooth Low Energy & Logi Bolt Receiver',
      'Multi-Device': 'Pair up to 3 devices with Easy-Switch',
      'Clicks': 'Quiet clicks (90% quieter vs standard)',
      'Warranty': '1 Year Hardware Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Graphite', color: 'Graphite', referencePrice: 9495, sku: 'MXM3S-GRPH' },
      { name: 'Pale Grey', color: 'Pale Grey', referencePrice: 9495, sku: 'MXM3S-GRY' },
    ],
    tags: ['logitech', 'mouse', 'wireless', 'ergonomic', 'mx master'],
  },
  {
    catalogId: 'MASTER-LOGI-K380-BT',
    productName: 'Logitech K380 Multi-Device Bluetooth Keyboard',
    brand: 'Logitech',
    model: 'K380',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 2895,
    currency: 'INR',
    description: 'Compact multi-device Bluetooth keyboard compatible with Windows, Mac, Android, iOS, and Chrome OS. Switch between 3 devices instantly.',
    specifications: 'Connectivity: Bluetooth 3.0 | Battery: 2x AAA (24 months) | Keys: Round Quiet Keys | Multi-Device: Connect 3 devices',
    specificationsObject: {
      'Connectivity': 'Bluetooth 3.0',
      'Multi-Device': 'Connect and switch between 3 devices instantly',
      'Battery Life': 'Up to 24 months (2x AAA)',
      'Compatible OS': 'Windows, macOS, Chrome OS, Android, iOS',
      'Key Type': 'Round quiet keys',
      'Dimensions': '279 x 130 x 16 mm',
      'Weight': '423 g',
      'Warranty': '1 Year Hardware Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Rose', color: 'Rose', referencePrice: 2895, sku: 'K380-ROSE' },
      { name: 'Blue Grey', color: 'Blue Grey', referencePrice: 2895, sku: 'K380-BLU' },
      { name: 'Off White', color: 'Off White', referencePrice: 2895, sku: 'K380-WHT' },
      { name: 'Black', color: 'Black', referencePrice: 2895, sku: 'K380-BLK' },
    ],
    tags: ['logitech', 'keyboard', 'bluetooth', 'wireless keyboard', 'multi-device'],
  },
  {
    catalogId: 'MASTER-CANON-IXUS-185',
    productName: 'Canon IXUS 185 Digital Compact Camera (20MP)',
    brand: 'Canon',
    model: 'IXUS 185',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 11490,
    currency: 'INR',
    description: 'Easy-to-use compact digital camera with 20MP sensor, 8x optical zoom, and Smart Auto mode for effortless quality shots.',
    specifications: 'Sensor: 20MP CCD | Zoom: 8x Optical | Display: 2.7" LCD | Video: 720p HD | Battery: Li-ion NB-11LH',
    specificationsObject: {
      'Effective Pixels': '20 Megapixel CCD',
      'Optical Zoom': '8x (28mm - 224mm equivalent)',
      'Display': '2.7-inch TFT LCD',
      'Video Resolution': '720p HD (1280x720) at 25fps',
      'Battery': 'Li-ion NB-11LH (rechargeable)',
      'Connectivity': 'USB, HDMI-mini',
      'Weight': '128 g (including battery)',
      'Warranty': '1 Year Canon India Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 11490, sku: 'IXUS185-BLK' },
      { name: 'Red', color: 'Red', referencePrice: 11490, sku: 'IXUS185-RED' },
    ],
    tags: ['canon', 'camera', 'digital camera', 'compact camera', 'ixus'],
  },
  {
    catalogId: 'MASTER-MI-PB-20000',
    productName: 'Mi Power Bank 3i 20000mAh (18W Fast Charge)',
    brand: 'Xiaomi (Mi)',
    model: 'Power Bank 3i 20000',
    category: 'Electronics',
    unit: 'Units',
    referencePrice: 1999,
    currency: 'INR',
    description: 'High-capacity lithium polymer power bank with 18W fast charging, triple output ports, and dual input support.',
    specifications: 'Capacity: 20000mAh | Output: 18W Fast Charge (Micro-USB input + USB-C input) | Ports: 3 USB-A + 1 USB-C',
    specificationsObject: {
      'Capacity': '20,000 mAh Lithium Polymer',
      'Input': 'Micro-USB (18W) + USB-C (18W)',
      'Output': '3x USB-A (Max 18W) + 1x USB-C',
      'Fast Charge': '18W Quick Charge 3.0',
      'Dimensions': '151 x 73.8 x 27.05 mm',
      'Weight': '440 g',
      'Warranty': '6 Months Brand Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 1999, sku: 'MI-PB3I-BLK' },
    ],
    tags: ['xiaomi', 'mi', 'power bank', 'powerbank', 'fast charge', 'portable charger'],
  },

  // ==========================================
  // IT HARDWARE - LAPTOPS
  // ==========================================
  {
    catalogId: 'MASTER-HP-PAV15-I5',
    productName: 'HP Pavilion 15 (13th Gen Intel Core i5, 16GB RAM, 512GB SSD)',
    brand: 'HP',
    model: 'Pavilion 15-eg3027TU',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 62490,
    currency: 'INR',
    description: '15.6-inch FHD IPS anti-glare display laptop powered by Intel Core i5-1335U, 16GB DDR4, 512GB NVMe M.2 SSD, Windows 11 Home & Office.',
    specifications: 'Processor: Intel Core i5-1335U (10 cores, up to 4.6 GHz) | RAM: 16GB DDR4-3200 | Storage: 512GB PCIe NVMe SSD | Display: 15.6" FHD IPS | OS: Windows 11',
    specificationsObject: {
      'Processor': 'Intel Core i5-1335U (10 cores, 12 threads, up to 4.6 GHz)',
      'Memory': '16 GB DDR4-3200 MHz RAM (1 x 16 GB)',
      'Internal Storage': '512 GB PCIe NVMe M.2 SSD',
      'Display': '39.6 cm (15.6") diagonal FHD (1920 x 1080) IPS, 250 nits',
      'Graphics': 'Intel Iris Xe Graphics',
      'Ports': '1 USB Type-C 10Gbps, 2 USB Type-A, 1 HDMI 2.1, 1 Audio combo',
      'Battery': '3-cell 41 Wh Li-ion, 65W Smart AC adapter',
      'Weight': '1.74 kg',
      'OS': 'Windows 11 Home with MS Office Home & Student 2021',
      'Warranty': '1 Year Onsite Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Natural Silver - 16GB / 512GB', color: 'Natural Silver', storage: '512GB SSD', ram: '16GB', referencePrice: 62490, sku: 'HP-PAV15-SLV' },
      { name: 'Fog Blue - 16GB / 512GB', color: 'Fog Blue', storage: '512GB SSD', ram: '16GB', referencePrice: 63990, sku: 'HP-PAV15-BLU' },
      { name: 'Natural Silver - 16GB / 1TB SSD', color: 'Natural Silver', storage: '1TB SSD', ram: '16GB', referencePrice: 68990, sku: 'HP-PAV15-1TB' },
    ],
    tags: ['hp', 'pavilion', 'laptop', 'intel core i5', 'computer', 'notebook'],
  },
  {
    catalogId: 'MASTER-DELL-LAT5440',
    productName: 'Dell Latitude 5440 (13th Gen Intel Core i7, 16GB RAM, 512GB SSD)',
    brand: 'Dell',
    model: 'Latitude 5440',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 84500,
    currency: 'INR',
    description: 'Enterprise-grade 14-inch business laptop with Intel Core i7-1355U, backlit keyboard, FHD camera and Windows 11 Pro.',
    specifications: 'Processor: Intel Core i7-1355U | RAM: 16GB DDR5 | Storage: 512GB PCIe M.2 SSD | Display: 14" FHD 250 nits | OS: Windows 11 Pro',
    specificationsObject: {
      'Processor': 'Intel Core i7-1355U (12 MB cache, 10 cores, up to 5.0 GHz)',
      'Memory': '16 GB DDR5 4800 MHz',
      'Storage': '512 GB M.2 2230 PCIe Gen4 NVMe SSD',
      'Display': '14.0" FHD (1920x1080) Non-Touch, AG, IPS, 250 nits',
      'Security': 'TPM 2.0, Fingerprint Reader',
      'Network': 'Intel Wi-Fi 6E AX211 + Bluetooth 5.3 + RJ-45 Gigabit Ethernet',
      'Weight': '1.36 kg',
      'OS': 'Windows 11 Pro',
      'Warranty': '3 Years ProSupport Onsite Service',
    },
    imageUrl: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard Grey - 16GB / 512GB', color: 'Grey', storage: '512GB SSD', ram: '16GB', referencePrice: 84500, sku: 'LAT5440-I7-16-512' },
      { name: 'Standard Grey - 32GB / 1TB', color: 'Grey', storage: '1TB SSD', ram: '32GB', referencePrice: 104000, sku: 'LAT5440-I7-32-1TB' },
    ],
    tags: ['dell', 'latitude', 'laptop', 'business laptop', 'intel core i7'],
  },
  {
    catalogId: 'MASTER-LENO-TP-E14',
    productName: 'Lenovo ThinkPad E14 Gen 5 (AMD Ryzen 5, 16GB RAM, 512GB SSD)',
    brand: 'Lenovo',
    model: 'ThinkPad E14 Gen 5',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 53990,
    currency: 'INR',
    description: 'Rugged enterprise-standard laptop tested against MIL-STD-810H standards with ergonomic TrackPoint keyboard.',
    specifications: 'Processor: AMD Ryzen 5 7530U | RAM: 16GB DDR4 | Storage: 512GB SSD | Display: 14" WUXGA IPS | OS: Windows 11',
    specificationsObject: {
      'Processor': 'AMD Ryzen 5 7530U (6 cores / 12 threads, up to 4.5 GHz)',
      'Memory': '16 GB DDR4-3200',
      'Storage': '512 GB SSD M.2 2242 PCIe NVMe',
      'Display': '14" WUXGA (1920x1200) IPS 300 nits Anti-glare',
      'Keyboard': 'Spill-resistant, 6-row backlit with TrackPoint',
      'Durability': 'MIL-STD-810H military certified',
      'OS': 'Windows 11 Home',
      'Warranty': '1 Year Premier Support',
    },
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Graphite Black - 16GB / 512GB', color: 'Graphite Black', storage: '512GB SSD', ram: '16GB', referencePrice: 53990, sku: 'TP-E14-G5' },
    ],
    tags: ['lenovo', 'thinkpad', 'e14', 'ryzen', 'laptop', 'office laptop'],
  },
  {
    catalogId: 'MASTER-ASUS-VIV-16-I5',
    productName: 'ASUS VivoBook 16 (Intel Core i5-12th Gen, 16GB RAM, 512GB SSD)',
    brand: 'ASUS',
    model: 'VivoBook 16 X1605ZA',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 52990,
    currency: 'INR',
    description: 'Thin and light 16-inch laptop with a vibrant display, Intel Core i5-1235U, and plenty of storage for everyday productivity.',
    specifications: 'Processor: Intel Core i5-1235U | RAM: 16GB DDR4 | Storage: 512GB NVMe SSD | Display: 16" FHD+ (1920x1200) IPS | OS: Windows 11',
    specificationsObject: {
      'Processor': 'Intel Core i5-1235U (10 cores up to 4.4 GHz)',
      'Memory': '16 GB DDR4-3200 MHz',
      'Storage': '512 GB M.2 PCIe NVMe SSD',
      'Display': '16-inch FHD+ (1920x1200) IPS, 60Hz, Anti-glare',
      'Graphics': 'Intel Iris Xe Graphics',
      'Ports': 'USB 3.2 Gen1 Type-A x2, USB 2.0 x1, USB-C (3.2 Gen1), HDMI, RJ45, 3.5mm Combo',
      'Battery': '42 Wh',
      'Weight': '1.88 kg',
      'OS': 'Windows 11 Home',
      'Warranty': '1 Year International Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Indie Black - 16GB / 512GB', color: 'Indie Black', storage: '512GB SSD', ram: '16GB', referencePrice: 52990, sku: 'ASUS-VB16-BLK' },
      { name: 'Cool Silver - 16GB / 512GB', color: 'Cool Silver', storage: '512GB SSD', ram: '16GB', referencePrice: 52990, sku: 'ASUS-VB16-SLV' },
    ],
    tags: ['asus', 'vivobook', 'laptop', 'intel', 'student laptop'],
  },
  {
    catalogId: 'MASTER-ACER-ASP5-I5',
    productName: 'Acer Aspire 5 (Intel Core i5-12th Gen, 16GB RAM, 512GB SSD)',
    brand: 'Acer',
    model: 'Aspire 5 A515-57',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 49990,
    currency: 'INR',
    description: 'Popular productivity laptop featuring Intel Core i5-1235U, 16GB RAM, FHD IPS display, and comprehensive connectivity.',
    specifications: 'Processor: Intel Core i5-1235U | RAM: 16GB | Storage: 512GB SSD | Display: 15.6" FHD IPS | OS: Windows 11',
    specificationsObject: {
      'Processor': 'Intel Core i5-1235U (10 cores, up to 4.4 GHz)',
      'Memory': '16 GB DDR4-3200 MHz',
      'Storage': '512 GB NVMe PCIe SSD',
      'Display': '15.6-inch FHD (1920x1080) IPS 60Hz, Anti-Glare',
      'Graphics': 'Intel Iris Xe Graphics',
      'Ports': '1 USB 3.2 Gen 2 Type-C, 1 USB 3.2 Gen 1, 1 USB 2.0, HDMI 2.0, RJ-45, SD Card Reader',
      'Battery': '55 Wh / 65W USB-C',
      'Weight': '1.9 kg',
      'Warranty': '1 Year International Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Steel Gray - 16GB / 512GB', color: 'Steel Gray', storage: '512GB SSD', ram: '16GB', referencePrice: 49990, sku: 'ACER-A5-GRY' },
    ],
    tags: ['acer', 'aspire', 'laptop', 'intel i5', 'student laptop'],
  },

  // ==========================================
  // IT HARDWARE - DESKTOPS, MONITORS, PERIPHERALS, NETWORKING
  // ==========================================
  {
    catalogId: 'MASTER-DELL-U2723QE',
    productName: 'Dell UltraSharp 27 4K USB-C Hub Monitor (U2723QE)',
    brand: 'Dell',
    model: 'U2723QE',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 54990,
    currency: 'INR',
    description: '27-inch 4K UHD monitor with IPS Black technology, 98% DCI-P3, USB-C 90W power delivery hub and RJ45.',
    specifications: 'Resolution: 3840x2160 @ 60Hz | Panel: IPS Black | Color: 98% DCI-P3 | Ports: USB-C Hub 90W PD, DP, HDMI, RJ45',
    specificationsObject: {
      'Screen Size': '27.0 inches (68.47 cm)',
      'Resolution': '4K UHD (3840 x 2160 at 60 Hz)',
      'Panel Type': 'IPS Black Technology',
      'Contrast Ratio': '2000:1 (typical)',
      'Connectivity': '1x HDMI, 1x DP in, 1x DP out, 1x USB-C 90W PD, RJ45 Ethernet',
      'Stand': 'Height-adjustable, tilt, swivel, pivot (90° rotation)',
      'Warranty': '3 Years Premium Panel Exchange',
    },
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Platinum Silver', color: 'Platinum Silver', referencePrice: 54990, sku: 'DELL-U2723QE' },
    ],
    tags: ['dell', 'ultrasharp', 'monitor', '4k', 'display', 'usb-c monitor'],
  },
  {
    catalogId: 'MASTER-LG-27MP400-B',
    productName: 'LG 27" Full HD IPS Monitor (27MP400-B)',
    brand: 'LG',
    model: '27MP400-B',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 14499,
    currency: 'INR',
    description: 'Budget-friendly 27-inch Full HD IPS monitor with 3-side frameless design, AMD FreeSync, and HDMI + VGA inputs.',
    specifications: 'Resolution: 1920x1080 | Panel: IPS | Refresh Rate: 75Hz | Response Time: 5ms | Ports: HDMI, D-Sub (VGA)',
    specificationsObject: {
      'Screen Size': '27 inches',
      'Resolution': 'FHD (1920 x 1080)',
      'Panel Type': 'IPS',
      'Refresh Rate': '75 Hz (with HDMI)',
      'Response Time': '5ms (GtG)',
      'Inputs': '1x HDMI 1.4, 1x D-Sub',
      'Brightness': '250 cd/m²',
      'Features': 'AMD FreeSync, 3-side borderless design',
      'Warranty': '1 Year Manufacturer Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 14499, sku: 'LG-27MP400B' },
    ],
    tags: ['lg', 'monitor', 'full hd', '27 inch', 'display'],
  },
  {
    catalogId: 'MASTER-SAMS-T7-1TB',
    productName: 'Samsung T7 Shield 1TB Portable External SSD (USB 3.2 Gen 2)',
    brand: 'Samsung',
    model: 'T7 Shield 1TB',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 9999,
    currency: 'INR',
    description: 'Rugged portable SSD with up to 1050 MB/s transfer speeds, IP65 water/dust resistance, and 3-meter drop resistance.',
    specifications: 'Capacity: 1TB | Speed: Up to 1050 MB/s read | Interface: USB 3.2 Gen 2 Type-C | Durability: IP65 Rated',
    specificationsObject: {
      'Capacity': '1 TB',
      'Interface': 'USB 3.2 Gen 2 (10Gbps), backward compatible',
      'Sequential Read': 'Up to 1,050 MB/s',
      'Sequential Write': 'Up to 1,000 MB/s',
      'Durability': 'IP65 Dust and Water Resistant, 3-meter drop resistance',
      'Encryption': 'AES 256-bit hardware encryption',
      'Warranty': '3 Years Limited Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black - 1TB', color: 'Black', storage: '1TB', referencePrice: 9999, sku: 'T7SH-1TB-BLK' },
      { name: 'Blue - 1TB', color: 'Blue', storage: '1TB', referencePrice: 9999, sku: 'T7SH-1TB-BLU' },
      { name: 'Beige - 1TB', color: 'Beige', storage: '1TB', referencePrice: 9999, sku: 'T7SH-1TB-BGE' },
    ],
    tags: ['samsung', 'ssd', 'external ssd', 'storage', 'backup', 'usb-c'],
  },
  {
    catalogId: 'MASTER-WD-PURPLE-2TB',
    productName: 'Western Digital Purple 2TB Surveillance HDD (SATA 6Gb/s)',
    brand: 'Western Digital',
    model: 'WD20PURZ',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 4799,
    currency: 'INR',
    description: 'Designed for 24/7 surveillance use with AllFrame AI technology and support for multiple simultaneous HD streams.',
    specifications: 'Capacity: 2TB | Interface: SATA 6Gb/s | Speed: 5400 RPM | Cache: 256MB | Use: CCTV / NVR / DVR',
    specificationsObject: {
      'Capacity': '2 TB',
      'Interface': 'SATA 6Gb/s',
      'RPM': '5400 RPM Class',
      'Cache Buffer': '256 MB',
      'Form Factor': '3.5-inch',
      'Use Case': 'Surveillance / 24x7 Always-On',
      'Streams Supported': 'Up to 64 HD streams simultaneously',
      'Warranty': '3 Years WD Limited Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '2TB Surveillance HDD', referencePrice: 4799, sku: 'WD-PURPLE-2TB' },
    ],
    tags: ['western digital', 'wd', 'hard drive', 'hdd', 'surveillance', 'storage'],
  },
  {
    catalogId: 'MASTER-KG-DDR4-8GB-3200',
    productName: 'Kingston FURY Beast 8GB DDR4-3200 MHz Desktop RAM',
    brand: 'Kingston',
    model: 'FURY Beast DDR4-3200',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 2499,
    currency: 'INR',
    description: 'Aggressive low-profile styling with Intel XMP 2.0 ready profiles and DDR4-3200 speeds for gaming and productivity PCs.',
    specifications: 'Capacity: 8GB | Type: DDR4 | Speed: 3200 MHz | Latency: CL16 | Voltage: 1.35V | Form: UDIMM',
    specificationsObject: {
      'Capacity': '8 GB (1 x 8 GB)',
      'Type': 'DDR4 SDRAM',
      'Speed': 'DDR4-3200 (PC4-25600)',
      'Latency': 'CL16-18-18',
      'Voltage': '1.35 V',
      'Form Factor': '288-pin UDIMM',
      'Compatibility': 'Intel XMP 2.0 / AMD Expo',
      'Warranty': 'Lifetime Kingston Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '8GB Single Module', referencePrice: 2499, sku: 'KG-FURY-8G-3200' },
      { name: '16GB (2x8GB) Kit', referencePrice: 4999, sku: 'KG-FURY-16G-3200' },
    ],
    tags: ['kingston', 'ram', 'ddr4', 'memory', 'fury beast'],
  },
  {
    catalogId: 'MASTER-CISCO-CBS110-24T',
    productName: 'Cisco Business 110 Series 24-Port Gigabit Unmanaged Switch',
    brand: 'Cisco',
    model: 'CBS110-24T-EU',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 12500,
    currency: 'INR',
    description: 'Plug-and-play 24-port Gigabit Ethernet switch for small-to-medium business workgroups.',
    specifications: 'Ports: 24x 10/100/1000 Gigabit Ethernet | Switching Capacity: 48 Gbps | Form Factor: 1U Rackmount / Desktop',
    specificationsObject: {
      'Ports': '24x 10/100/1000 Mbps RJ-45 ports',
      'Switching Capacity': '48 Gbps wire-speed forwarding',
      'Forwarding Rate': '35.7 Mpps',
      'Power Consumption': '16.7W Energy Efficient Ethernet (802.3az)',
      'Mounting': 'Rackmount ears and rubber feet included',
      'Warranty': 'Limited Lifetime Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard 24-Port', referencePrice: 12500, sku: 'CBS110-24T' },
    ],
    tags: ['cisco', 'switch', 'network', 'gigabit', 'ethernet', 'rackmount'],
  },
  {
    catalogId: 'MASTER-TP-AX1800-WIFI6',
    productName: 'TP-Link Archer AX1800 Wi-Fi 6 Dual-Band Router',
    brand: 'TP-Link',
    model: 'Archer AX21',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 3499,
    currency: 'INR',
    description: 'Wi-Fi 6 router delivering up to 1800 Mbps, with OFDMA technology, advanced security (WPA3), and MU-MIMO for multiple devices.',
    specifications: 'Wi-Fi Speed: AX1800 (1200+574 Mbps) | Standard: Wi-Fi 6 (802.11ax) | Ports: 1x WAN + 4x LAN Gigabit | Security: WPA3',
    specificationsObject: {
      'Wi-Fi Speed': 'AX1800: 1201 Mbps (5GHz) + 574 Mbps (2.4GHz)',
      'Standard': 'IEEE 802.11ax/ac/n/g/b/a',
      'Processor': '1GHz Dual-Core CPU',
      'Ports': '1x WAN Gigabit + 4x LAN Gigabit',
      'Antennas': '4x High-Gain External Antennas',
      'Security': 'WPA3, SPI Firewall, Access Control',
      'Features': 'OFDMA, MU-MIMO, Beamforming',
      'Warranty': '3 Years TP-Link Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard White', color: 'White', referencePrice: 3499, sku: 'TP-AX1800' },
    ],
    tags: ['tp-link', 'router', 'wifi 6', 'wireless router', 'networking'],
  },
  {
    catalogId: 'MASTER-ZEBRA-ZT411-LABEL',
    productName: 'Zebra ZT411 Industrial Direct Thermal / Thermal Transfer Label Printer',
    brand: 'Zebra',
    model: 'ZT411',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 45000,
    currency: 'INR',
    description: 'Industrial-grade label printer designed for high-volume environments with color LCD, USB, Ethernet, Bluetooth, and Wi-Fi connectivity.',
    specifications: 'Print Width: 4 inches (104mm) | Resolution: 203 or 300 DPI | Speed: Up to 356mm/s | Connectivity: USB, Ethernet, Bluetooth, Wi-Fi',
    specificationsObject: {
      'Print Method': 'Direct Thermal / Thermal Transfer',
      'Print Width': '4 inches (104 mm) maximum',
      'Print Speed': 'Up to 356 mm/s (14 inches/s)',
      'Resolution': '203 dpi or 300 dpi',
      'Connectivity': 'USB 2.0, Gigabit Ethernet, Bluetooth 4.1 LE, Wi-Fi 802.11ac',
      'Media Handling': 'Printout, Tear-off, Peel and present with liner take-up',
      'Display': '4.3-inch colour touch screen',
      'Warranty': '1 Year Zebra Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'ZT411 203dpi', referencePrice: 45000, sku: 'ZT411-203DPI' },
      { name: 'ZT411 300dpi', referencePrice: 48000, sku: 'ZT411-300DPI' },
    ],
    tags: ['zebra', 'label printer', 'barcode printer', 'industrial printer'],
  },
  {
    catalogId: 'MASTER-APC-UPS-600VA',
    productName: 'APC Back-UPS 600VA (360W) Line-Interactive UPS',
    brand: 'APC',
    model: 'BX600C-IN',
    category: 'IT Hardware',
    unit: 'Units',
    referencePrice: 3990,
    currency: 'INR',
    description: 'Entry-level line-interactive UPS providing backup power and automatic voltage regulation for desktops, routers, and workstations.',
    specifications: 'Capacity: 600 VA / 360W | Type: Line-Interactive | Outlets: 4 UPS + 4 Surge | Runtime: Approx. 5-7 min full load | Battery: 7 Ah',
    specificationsObject: {
      'Capacity': '600 VA / 360 Watts',
      'UPS Type': 'Line-Interactive with AVR',
      'Outlets': '4x Battery Backup + Surge + 4x Surge Only',
      'Battery': 'Sealed Lead Acid 12V 7Ah (user-replaceable)',
      'Transfer Time': '< 6 ms',
      'Communication': '1x USB (Management Port)',
      'Warranty': '2 Years APC Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '600VA / 360W', referencePrice: 3990, sku: 'APC-BX600' },
    ],
    tags: ['apc', 'ups', 'uninterruptible power supply', 'power backup'],
  },

  // ==========================================
  // OFFICE EQUIPMENT - PRINTERS, SHREDDERS, PROJECTORS
  // ==========================================
  {
    catalogId: 'MASTER-HP-LJ-4104FDW',
    productName: 'HP LaserJet Pro MFP 4104fdw All-in-One Monochrome Laser Printer',
    brand: 'HP',
    model: 'LaserJet Pro MFP 4104fdw',
    category: 'Office Equipment',
    unit: 'Units',
    referencePrice: 42999,
    currency: 'INR',
    description: 'High-speed multifunction enterprise printer (Print, Scan, Copy, Fax) with automatic two-sided printing and dual-band Wi-Fi.',
    specifications: 'Print Speed: Up to 40 ppm | Functions: Print, Copy, Scan, Fax | Connectivity: Dual-band Wi-Fi, Gigabit Ethernet, USB | Duplex: Auto Duplex',
    specificationsObject: {
      'Functions': 'Print, Copy, Scan, Fax',
      'Print Speed (Black)': 'Up to 40 ppm (A4)',
      'Duplex Printing': 'Automatic (standard)',
      'Duty Cycle (Monthly)': 'Up to 80,000 pages',
      'Scan Resolution': 'Up to 1200 x 1200 dpi',
      'ADF Capacity': '50 sheets with dual-side pass',
      'Connectivity': '1 Hi-Speed USB 2.0; 1 Gigabit Ethernet; Wi-Fi 802.11b/g/n',
      'Warranty': '1 Year HP Onsite Commercial Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard White', referencePrice: 42999, sku: 'HP-MFP4104' },
    ],
    tags: ['hp', 'printer', 'laserjet', 'copier', 'scanner', 'multifunction'],
  },
  {
    catalogId: 'MASTER-EPSON-L3250',
    productName: 'Epson EcoTank L3250 Wi-Fi All-in-One Ink Tank Printer',
    brand: 'Epson',
    model: 'EcoTank L3250',
    category: 'Office Equipment',
    unit: 'Units',
    referencePrice: 14499,
    currency: 'INR',
    description: 'Cost-efficient refillable ink tank color printer with Wi-Fi Direct and mobile app support for everyday office documentation.',
    specifications: 'Type: Ink Tank All-in-One (Print, Scan, Copy) | Yield: Up to 4500 black / 7500 color pages | Connectivity: Wi-Fi, USB',
    specificationsObject: {
      'Print Speed': 'Up to 33.0 ppm (Black) / 15.0 ppm (Color)',
      'Print Resolution': '5760 x 1440 dpi',
      'Page Yield': '4,500 pages (Black) and 7,500 pages (Color)',
      'Connectivity': 'Wi-Fi, Wi-Fi Direct, USB 2.0',
      'Paper Sizes': 'A4, A5, A6, B5, Letter, Envelopes',
      'Warranty': '1 Year or 30,000 pages standard warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard Black', referencePrice: 14499, sku: 'EPSON-L3250' },
    ],
    tags: ['epson', 'ecotank', 'printer', 'ink tank', 'color printer'],
  },
  {
    catalogId: 'MASTER-CANON-PIXMA-G3770',
    productName: 'Canon PIXMA G3770 MegaTank Wireless All-In-One Ink Tank Printer',
    brand: 'Canon',
    model: 'PIXMA G3770',
    category: 'Office Equipment',
    unit: 'Units',
    referencePrice: 15990,
    currency: 'INR',
    description: 'High-volume wireless ink tank printer with premium 4-color ink system, up to 6000 black and 7700 color page yields.',
    specifications: 'Type: Ink Tank MFP (Print, Scan, Copy) | Connectivity: Wi-Fi + USB | Yield: 6000 BW + 7700 Color pages | Resolution: 4800x1200 dpi',
    specificationsObject: {
      'Print Functions': 'Print, Copy, Scan',
      'Print Speed': '11 ipm (B&W), 6 ipm (Color)',
      'Print Resolution': '4800 x 1200 dpi',
      'Connectivity': 'Wi-Fi, USB 2.0',
      'Ink Tank Yield': '6,000 pages (Black) and 7,700 pages (Color)',
      'Paper Sizes': 'A4, A5, B5, LTR, Legal, Photo 4x6',
      'Warranty': '1 Year Carry-In Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 15990, sku: 'CANON-G3770-BLK' },
      { name: 'White', color: 'White', referencePrice: 15990, sku: 'CANON-G3770-WHT' },
    ],
    tags: ['canon', 'pixma', 'ink tank', 'printer', 'wireless', 'megatank'],
  },
  {
    catalogId: 'MASTER-FEL-SHRED-79CI',
    productName: 'Fellowes Powershred 79Ci 100% Jam Proof Cross-Cut Paper Shredder',
    brand: 'Fellowes',
    model: 'Powershred 79Ci',
    category: 'Office Equipment',
    unit: 'Units',
    referencePrice: 28500,
    currency: 'INR',
    description: 'Heavy duty office paper shredder with 100% Jam Proof System, SafeSense Technology, and SilentShred ultra-quiet performance.',
    specifications: 'Capacity: 16 sheets per pass | Cut Type: Cross-Cut (P-4 security) | Bin Capacity: 23 Litres | Run Time: 20 minutes',
    specificationsObject: {
      'Sheet Capacity': '16 sheets per pass (70gsm)',
      'Cut Type': 'Cross-cut (4 x 38mm particles)',
      'Security Level': 'DIN P-4',
      'Shreds': 'Paper, staples, credit cards, paper clips, CDs/DVDs',
      'Bin Capacity': '23 Litres pull-out waste bin',
      'Safety': 'SafeSense technology stops shredding when hands touch paper entry',
      'Warranty': '2 Years Machine / 5 Years Cutter Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black/Dark Chrome', referencePrice: 28500, sku: 'FEL-79CI' },
    ],
    tags: ['shredder', 'fellowes', 'paper shredder', 'office equipment', 'security'],
  },
  {
    catalogId: 'MASTER-EPSON-EB-W52',
    productName: 'Epson EB-W52 3LCD Business Projector (4000 Lumens, WXGA)',
    brand: 'Epson',
    model: 'EB-W52',
    category: 'Office Equipment',
    unit: 'Units',
    referencePrice: 52999,
    currency: 'INR',
    description: 'High-brightness 3LCD projector for office presentations with WXGA resolution, HDMI, USB display, and wired network support.',
    specifications: 'Brightness: 4000 lumens white/colour | Resolution: WXGA (1280x800) | Throw Ratio: 1.33 - 1.60:1 | Connectivity: HDMI, USB-B, D-Sub, LAN',
    specificationsObject: {
      'Brightness': '4,000 lumens (White and Color)',
      'Resolution': 'WXGA (1280 x 800)',
      'Projection System': '3LCD (3 x 0.59" TFT Polysilicon)',
      'Throw Ratio': '1.33 - 1.60:1 (Standard)',
      'Connectivity': 'HDMI, USB Type-B (USB Display), D-Sub, Wired LAN, RS-232C',
      'Lamp Life': 'Up to 12,000 hours (Eco Mode)',
      'Keystone Correction': '±30° vertical',
      'Warranty': '2 Years On-Site Lamp Swap Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard White', referencePrice: 52999, sku: 'EPSON-EBW52' },
    ],
    tags: ['epson', 'projector', 'office projector', 'presentation', 'lcd projector'],
  },
  {
    catalogId: 'MASTER-SCAN-CANON-DR-C230',
    productName: 'Canon imageFORMULA DR-C230 Office Document Scanner',
    brand: 'Canon',
    model: 'DR-C230',
    category: 'Office Equipment',
    unit: 'Units',
    referencePrice: 29999,
    currency: 'INR',
    description: 'Compact double-sided document scanner with 30 ppm/60 ipm speed, 60-sheet ADF, and intelligent barcode detection.',
    specifications: 'Speed: 30 ppm / 60 ipm | ADF: 60 sheets | Resolution: 600 dpi | Scan to: PDF, JPEG, TIFF, Word, Excel | Connectivity: USB 3.0',
    specificationsObject: {
      'Scanning Speed': '30 ppm / 60 ipm (Simplex/Duplex at 200/300 dpi)',
      'ADF Capacity': '60 sheets',
      'Optical Resolution': '600 dpi',
      'Output Formats': 'PDF (searchable), JPEG, TIFF, DOCX, XLSX',
      'Connectivity': 'USB 3.0',
      'Document Feeder': 'A8 to Legal, 52-209 gsm',
      'Warranty': '1 Year Carry-in Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'White/Black', referencePrice: 29999, sku: 'CANON-DRC230' },
    ],
    tags: ['canon', 'scanner', 'document scanner', 'adf scanner', 'office scanner'],
  },

  // ==========================================
  // FURNITURE - CHAIRS, DESKS, CABINETS
  // ==========================================
  {
    catalogId: 'MASTER-FURN-CHAIR-ERGOMESH',
    productName: 'Ergonomic High-Back Breathable Mesh Office Chair',
    brand: 'Green Soul / Featherlite',
    model: 'ErgoPro Mesh Series',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 14500,
    currency: 'INR',
    description: 'Professional ergonomic executive chair with dynamic lumbar support, 3D adjustable armrests, multi-lock recline, and Class-4 gas lift.',
    specifications: 'Backrest: Breathable Korean Mesh | Base: Heavy Duty Chrome Metal | Lift: Class 4 Gas Lift | Mechanism: Multi-lock synchro-tilt',
    specificationsObject: {
      'Material': 'Breathable High Density Mesh + Moulded Foam Cushion',
      'Armrests': '3D Adjustable (Height, Depth, Angle)',
      'Headrest': '2D Adjustable (Height and Angle)',
      'Lumbar Support': 'Self-adjusting adaptive lumbar cushion',
      'Recline Angle': '90° to 135° with 3-position lock',
      'Weight Capacity': 'Up to 135 kg',
      'Certification': 'BIFMA Certified components',
      'Warranty': '3 Years Comprehensive Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1580481077195-c22845348981?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'All Black Mesh', color: 'Black', referencePrice: 14500, sku: 'ERGO-CHR-BLK' },
      { name: 'Grey Frame & Black Mesh', color: 'Grey/Black', referencePrice: 15500, sku: 'ERGO-CHR-GRY' },
    ],
    tags: ['chair', 'ergonomic chair', 'office chair', 'furniture', 'mesh chair'],
  },
  {
    catalogId: 'MASTER-FURN-CHAIR-EXEC',
    productName: 'High-Back Executive Leatherette Office Chair',
    brand: 'Godrej Interio / Wipro',
    model: 'Executive Pro Series',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 18000,
    currency: 'INR',
    description: 'Classic high-back executive chair with premium leatherette upholstery, polished chrome armrests, and multi-lock tilt mechanism.',
    specifications: 'Upholstery: Leatherette | Armrests: Polished Chrome | Mechanism: Multi-lock tilt | Weight Capacity: 120 kg',
    specificationsObject: {
      'Upholstery': 'Premium leatherette (PU coated fabric)',
      'Armrests': 'Polished chrome fixed armrests with PU pads',
      'Mechanism': 'Multi-function tilt with tension adjustment',
      'Gas Lift': 'Class 4 heavy-duty pneumatic gas lift',
      'Base': '5-star nylon base with twin-wheel casters (carpet/floor)',
      'Seat Dimensions': 'Approx. 50cm W x 45cm D',
      'Weight Capacity': '120 kg',
      'Warranty': '2 Years Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1580481077195-c22845348981?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black Leatherette', color: 'Black', referencePrice: 18000, sku: 'EXEC-CHR-BLK' },
    ],
    tags: ['chair', 'executive chair', 'office chair', 'furniture', 'leatherette'],
  },
  {
    catalogId: 'MASTER-FURN-CHAIR-VISITOR',
    productName: 'Visitor Chair with Padded Seat and Back (Set of 2)',
    brand: 'Zuari / Interio',
    model: 'Visitor Comfort Series',
    category: 'Furniture',
    unit: 'Set',
    referencePrice: 3500,
    currency: 'INR',
    description: 'Set of 2 fixed-leg padded visitor chairs suitable for reception areas, conference rooms, and waiting areas.',
    specifications: 'Quantity: 2 chairs per set | Upholstery: Fabric / Rexine | Frame: MS Powder Coated | Seat Width: ~47cm | Weight Capacity: 100kg each',
    specificationsObject: {
      'Upholstery': 'High-density foam with fabric / rexine cover',
      'Frame': 'Mild Steel powder-coated tubular legs',
      'Seat Width': 'Approx. 47 cm',
      'Seat Height': 'Approx. 45 cm',
      'Weight Capacity': '100 kg per chair',
      'Assembly': 'Minimal assembly required',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1580481077195-c22845348981?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black / Grey - Set of 2', color: 'Black', referencePrice: 3500, sku: 'VIS-CHR-2SET-BLK' },
      { name: 'Blue / Black - Set of 2', color: 'Blue/Black', referencePrice: 3500, sku: 'VIS-CHR-2SET-BLU' },
    ],
    tags: ['chair', 'visitor chair', 'furniture', 'reception chair', 'office chair'],
  },
  {
    catalogId: 'MASTER-FURN-DESK-MOTORIZED',
    productName: 'Motorized Dual-Motor Height Adjustable Standing Desk (140x70 cm)',
    brand: 'ErgoDesk',
    model: 'Dual-Motor Series 2',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 28900,
    currency: 'INR',
    description: 'Electric sit-stand desk with dual quiet motors, digital memory handset with 4 presets, anti-collision sensor, and cable management tray.',
    specifications: 'Dimensions: 140cm x 70cm x 2.5cm | Height Range: 62cm - 128cm | Load Capacity: 120 kg | Motors: Dual Motors (<45dB)',
    specificationsObject: {
      'Tabletop Dimensions': '1400 mm x 700 mm x 25 mm Engineered Wood',
      'Frame Material': 'Industrial-grade cold-rolled carbon steel',
      'Height Range': '620 mm to 1280 mm',
      'Motors': 'Dual synchronous electric motors',
      'Control Panel': 'LED display with 4 programmable memory presets',
      'Anti-Collision': 'Integrated gyro-sensor collision detection',
      'Weight Capacity': '120 kg (265 lbs)',
      'Warranty': '5 Years on Frame & Motors',
    },
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Walnut Top / Black Frame', color: 'Walnut/Black', referencePrice: 28900, sku: 'STAND-DSK-WLN' },
      { name: 'Oak Top / White Frame', color: 'Oak/White', referencePrice: 28900, sku: 'STAND-DSK-OAK' },
      { name: 'Matte Black / Black Frame', color: 'Full Black', referencePrice: 28900, sku: 'STAND-DSK-BLK' },
    ],
    tags: ['desk', 'standing desk', 'ergonomic desk', 'furniture', 'motorized desk'],
  },
  {
    catalogId: 'MASTER-FURN-DESK-COMPUTER',
    productName: 'Computer Desk with Keyboard Tray and CPU Stand (120x60 cm)',
    brand: 'Nilkamal / Zuari',
    model: 'WorkPro 1200',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 7500,
    currency: 'INR',
    description: 'Office computer workstation table with sliding keyboard tray, side CPU trolley, and laminated MDF top in standard dimensions.',
    specifications: 'Dimensions: 120cm x 60cm x 75cm | Material: Prelaminated Particle Board (MDF) | Features: Keyboard Tray, CPU Stand, Cable Hole',
    specificationsObject: {
      'Dimensions': '1200 mm (L) x 600 mm (W) x 750 mm (H)',
      'Material': 'Pre-laminated Medium Density Fibre Board (MDF)',
      'Features': 'Sliding keyboard tray, side CPU trolley, central cable hole',
      'Finish': 'Melamine laminate (scratch & stain resistant)',
      'Assembly': 'Self-assembly with hardware included',
      'Weight Capacity': '50 kg desktop load',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Dark Wenge', color: 'Dark Wenge', referencePrice: 7500, sku: 'COMP-DSK-WNG' },
      { name: 'Classic Oak', color: 'Oak', referencePrice: 7500, sku: 'COMP-DSK-OAK' },
    ],
    tags: ['computer table', 'desk', 'furniture', 'office desk', 'workstation'],
  },
  {
    catalogId: 'MASTER-FURN-CABINET-STEEL',
    productName: 'Godrej 4-Drawer Steel Filing & Storage Cabinet',
    brand: 'Godrej Interio',
    model: 'Storewel 4D',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 18200,
    currency: 'INR',
    description: 'Heavy gauge steel vertical filing cabinet with centralized locking system, anti-tilt mechanism, and smooth ball-bearing runners.',
    specifications: 'Drawers: 4 full extension drawers | Material: CRCA Steel (0.8mm) | Lock: Central key lock | Finish: Powder Coated',
    specificationsObject: {
      'Dimensions': '1320 mm (H) x 470 mm (W) x 620 mm (D)',
      'Material': 'High grade CRCA steel with epoxy polyester powder coat',
      'Drawer Mechanism': 'Heavy-duty 3-stage telescopic ball-bearing sliders',
      'Locking': 'Master central locking mechanism',
      'Capacity': '40 kg weight capacity per drawer',
      'Warranty': '1 Year Godrej Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Office Grey', color: 'Grey', referencePrice: 18200, sku: 'GODR-4D-GRY' },
    ],
    tags: ['godrej', 'cabinet', 'storage', 'filing cabinet', 'steel furniture'],
  },
  {
    catalogId: 'MASTER-FURN-CONF-TABLE-8',
    productName: 'Conference Room Table - 8 Seater (240x90 cm) with Cable Management',
    brand: 'Durian / Nilkamal',
    model: 'Executive Conference 2400',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 35000,
    currency: 'INR',
    description: 'Premium boat-shaped 8-seater conference table with central cable management grommet, MDF top with veneer finish, and metal base.',
    specifications: 'Dimensions: 240cm x 90cm x 75cm | Seats: 8-10 persons | Material: MDF + Veneer / Laminate | Features: Central cable grommet',
    specificationsObject: {
      'Dimensions': '2400 mm (L) x 900 mm (W) x 750 mm (H)',
      'Seating Capacity': '8 to 10 persons',
      'Material': 'MDF + Veneer laminate with ABS edge banding',
      'Base': 'Heavy-duty metal frame with chrome finish',
      'Cable Management': 'Central flip-top cable management grommet',
      'Finish': 'Woodgrain laminate, scratch-resistant',
      'Assembly': 'Professional assembly required',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Dark Wenge', color: 'Dark Wenge', referencePrice: 35000, sku: 'CONF-TBL-WNG-8' },
      { name: 'Classic White', color: 'White', referencePrice: 35000, sku: 'CONF-TBL-WHT-8' },
    ],
    tags: ['conference table', 'meeting table', 'furniture', 'office table'],
  },
  {
    catalogId: 'MASTER-FURN-BOOKSHELF-5TIER',
    productName: '5-Tier Steel Bookshelf / Storage Rack (90x30x180 cm)',
    brand: 'Spacewood / Nilkamal',
    model: 'StoreMax 5-Tier',
    category: 'Furniture',
    unit: 'Units',
    referencePrice: 4500,
    currency: 'INR',
    description: 'Heavy-duty 5-tier adjustable steel shelving unit for office storage, archives, and general storage.',
    specifications: 'Dimensions: 90cm W x 30cm D x 180cm H | Tiers: 5 adjustable shelves | Material: Galvanised / Powder-coated steel | Load: 80kg per shelf',
    specificationsObject: {
      'Dimensions': '900 mm (W) x 300 mm (D) x 1800 mm (H)',
      'Number of Shelves': '5 adjustable shelves',
      'Material': 'Galvanized steel with powder-coated epoxy finish',
      'Weight Capacity': '80 kg per shelf',
      'Assembly': 'Tool-free bolt and nut assembly',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Grey', color: 'Grey', referencePrice: 4500, sku: 'BKSHELF-5T-GRY' },
    ],
    tags: ['bookshelf', 'shelf', 'storage rack', 'furniture', 'steel shelf'],
  },

  // ==========================================
  // STATIONERY
  // ==========================================
  {
    catalogId: 'MASTER-STAT-PAPER-A4-75',
    productName: 'JK Copier A4 Paper 75 GSM (Carton of 5 Reams / 2500 Sheets)',
    brand: 'JK Paper',
    model: 'JK Copier 75 GSM',
    category: 'Stationery',
    unit: 'Box',
    referencePrice: 1450,
    currency: 'INR',
    description: 'High brightness premium photocopy and laser printing paper carton containing 5 reams (500 sheets each). Jam-free performance.',
    specifications: 'Size: A4 (210 x 297 mm) | GSM: 75 GSM | Brightness: 98% ISO | Quantity: 5 Reams (2,500 Sheets total)',
    specificationsObject: {
      'Sheet Size': 'A4 (210 mm x 297 mm)',
      'Substance (GSM)': '75 GSM',
      'Brightness': '98% ISO Brightness',
      'Opacity': '92%',
      'Packaging': 'Carton box containing 5 Reams of 500 sheets',
      'Compatibility': 'Laser, Inkjet, High-speed offset, Photocopy machines',
    },
    imageUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '5-Ream Box (2500 Sheets)', referencePrice: 1450, sku: 'JK-A4-75-BOX' },
    ],
    tags: ['jk paper', 'a4 paper', 'paper', 'stationery', 'copier paper', 'printing paper'],
  },
  {
    catalogId: 'MASTER-STAT-PEN-REYNOLDS-BOX',
    productName: 'Reynolds 045 Fine Carbure Ball Pen (Box of 50 Pens)',
    brand: 'Reynolds',
    model: '045 Fine Carbure',
    category: 'Stationery',
    unit: 'Box',
    referencePrice: 350,
    currency: 'INR',
    description: 'Classic Indian office ballpoint pen delivering a smooth, consistent writing experience. Suitable for everyday office use.',
    specifications: 'Type: Ballpoint Pen | Tip: 0.5mm Fine | Ink: Long-lasting carbure ink | Quantity: 50 pens per box | Colors: Blue / Black',
    specificationsObject: {
      'Pen Type': 'Ballpoint',
      'Tip Size': '0.5 mm Fine',
      'Ink Type': 'Smooth carbure oil-based ink',
      'Quantity per Box': '50 pens',
      'Grip': 'Comfortable textured grip',
    },
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Blue Ink - Box of 50', color: 'Blue', referencePrice: 350, sku: 'REY-045-BLU-50' },
      { name: 'Black Ink - Box of 50', color: 'Black', referencePrice: 350, sku: 'REY-045-BLK-50' },
    ],
    tags: ['reynolds', 'pen', 'ballpoint pen', 'stationery', 'office supplies'],
  },
  {
    catalogId: 'MASTER-STAT-NOTEBOOK-A4-192',
    productName: 'Classmate Notebook A4 Single Line 192 Pages (Pack of 6)',
    brand: 'ITC Classmate',
    model: 'Classmate A4 SL 192',
    category: 'Stationery',
    unit: 'Pack',
    referencePrice: 300,
    currency: 'INR',
    description: 'Widely used school-grade single-line ruled A4 notebook with FSC-certified paper, smooth writing surface, and durable printed cover.',
    specifications: 'Size: A4 | Pages: 192 (96 leaves) | Ruling: Single Line | Paper: 60 GSM | Quantity: 6 Notebooks per pack',
    specificationsObject: {
      'Sheet Size': 'A4 (210 x 297 mm)',
      'Pages': '192 pages (96 leaves)',
      'Ruling': 'Single line',
      'Paper GSM': '60 GSM writing paper',
      'Cover': 'Thick cardboard cover',
      'Quantity per Pack': '6 Notebooks',
    },
    imageUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Pack of 6 - Assorted Covers', referencePrice: 300, sku: 'CM-NB-A4-6PK' },
    ],
    tags: ['classmate', 'notebook', 'stationery', 'office supplies', 'writing'],
  },
  {
    catalogId: 'MASTER-STAT-BOARD-MAG-4X3',
    productName: 'Magnetic Dry Erase Whiteboard (4 x 3 Feet) with Aluminum Frame',
    brand: 'Alkosign / Pragati Systems',
    model: 'Prima Series 4x3',
    category: 'Stationery',
    unit: 'Units',
    referencePrice: 2200,
    currency: 'INR',
    description: 'Smooth magnetic surface whiteboard for meetings and conferences. Includes marker tray and mounting kit.',
    specifications: 'Dimensions: 120 cm x 90 cm (4x3 ft) | Surface: Resin-coated magnetic steel | Frame: Anodized aluminum with ABS corners',
    specificationsObject: {
      'Dimensions': '1200 mm x 900 mm (4 ft x 3 ft)',
      'Surface': 'High-gloss magnetic white resin-coated steel sheet',
      'Frame': 'Satin finish alloy aluminum frame with engineered ABS corners',
      'Included Accessories': 'Detachable marker tray, wall mounting hardware',
      'Warranty': '2 Years on surface writing durability',
    },
    imageUrl: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '4x3 Feet', referencePrice: 2200, sku: 'WB-MAG-4X3' },
      { name: '6x4 Feet', referencePrice: 3800, sku: 'WB-MAG-6X4' },
    ],
    tags: ['whiteboard', 'magnetic board', 'stationery', 'meeting room', 'office board'],
  },
  {
    catalogId: 'MASTER-STAT-STAPLER-KANGARO',
    productName: 'Kangaro DP-480 Desk Heavy Duty Stapler (90 Sheet Capacity)',
    brand: 'Kangaro',
    model: 'DP-480',
    category: 'Stationery',
    unit: 'Units',
    referencePrice: 450,
    currency: 'INR',
    description: 'Heavy-duty desktop stapler for high-volume office document binding, compatible with standard 26/6 and 24/6 staples.',
    specifications: 'Capacity: 90 sheets per staple | Staples: 26/6 and 24/6 | Magazine Depth: 50 staples | Throat Depth: 80mm',
    specificationsObject: {
      'Sheet Capacity': '90 sheets (70 GSM paper)',
      'Staple Size': '26/6 and 24/6 standard staples',
      'Magazine Capacity': '50 staples',
      'Throat Depth': '80 mm',
      'Material': 'Metal body with ABS base',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Black', color: 'Black', referencePrice: 450, sku: 'KANG-DP480-BLK' },
    ],
    tags: ['stapler', 'kangaro', 'office supplies', 'stationery', 'heavy duty'],
  },
  {
    catalogId: 'MASTER-STAT-MARKER-CAMLIN',
    productName: 'Camlin Permanent Marker Pen - Assorted (Pack of 10)',
    brand: 'Camlin',
    model: 'Permanent Marker',
    category: 'Stationery',
    unit: 'Pack',
    referencePrice: 160,
    currency: 'INR',
    description: 'High-quality permanent markers with quick-drying waterproof ink, suitable for all surfaces including paper, glass, plastic, metal.',
    specifications: 'Tip Type: Bullet / Fine | Ink: Permanent waterproof | Quantity: 10 assorted colors | Cap: Snap-on',
    specificationsObject: {
      'Tip Type': 'Bullet tip / Fine',
      'Ink': 'Quick-drying permanent waterproof ink',
      'Colors': '10 assorted (Red, Blue, Black, Green, Orange, etc.)',
      'Surface': 'Works on paper, glass, plastic, metal, wood',
    },
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Pack of 10 Assorted Colors', referencePrice: 160, sku: 'CAMLIN-MARKER-10' },
    ],
    tags: ['camlin', 'marker', 'permanent marker', 'stationery', 'office supplies'],
  },
  {
    catalogId: 'MASTER-STAT-FOLDER-ARCH',
    productName: 'Archival Box File Folder (Pack of 10)',
    brand: 'Solo / Leitz',
    model: 'Ring Binder Box File',
    category: 'Stationery',
    unit: 'Pack',
    referencePrice: 750,
    currency: 'INR',
    description: 'Heavy-duty archival box file with 2-inch spine, finger ring pull, and label holder for organised document filing.',
    specifications: 'Size: A4 | Spine Width: 5cm (2 inch) | Closure: Latch clip | Quantity: 10 per pack | Colors: Assorted',
    specificationsObject: {
      'Document Size': 'A4 and Foolscap',
      'Spine Width': '50 mm (2 inch)',
      'Closure': 'Metal latch with lever arch mechanism',
      'Label Holder': 'Detachable label holder',
      'Quantity per Pack': '10 Box Files',
    },
    imageUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Pack of 10 Assorted', referencePrice: 750, sku: 'BOXFILE-10PK' },
    ],
    tags: ['box file', 'arch file', 'folder', 'stationery', 'filing'],
  },
  {
    catalogId: 'MASTER-STAT-ENVELOPE-DL',
    productName: 'DL White Peel & Seal Window Envelopes (Box of 500)',
    brand: 'Bong / Lotus',
    model: 'DL Window Envelope',
    category: 'Stationery',
    unit: 'Box',
    referencePrice: 620,
    currency: 'INR',
    description: 'Standard DL window envelopes with self-seal peel-and-seal adhesive strip, suitable for business correspondence.',
    specifications: 'Size: DL (220 x 110 mm) | Window: Left-aligned | Seal: Peel & Seal | Quantity: 500 per box | Paper: 90 GSM',
    specificationsObject: {
      'Size': 'DL (220 mm x 110 mm)',
      'Window': 'Left-window (45 x 90 mm) with glassine film',
      'Sealing': 'Self-seal peel-and-stick adhesive',
      'Paper Weight': '90 GSM bond paper',
      'Quantity': '500 envelopes per box',
    },
    imageUrl: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Box of 500', referencePrice: 620, sku: 'ENVELOPE-DL-500' },
    ],
    tags: ['envelope', 'stationery', 'office supplies', 'business envelope', 'mailing'],
  },

  // ==========================================
  // SAFETY EQUIPMENT
  // ==========================================
  {
    catalogId: 'MASTER-SAFE-3M-HELMET-H700',
    productName: '3M H-700 Series Vented Hard Hat / Industrial Safety Helmet',
    brand: '3M',
    model: 'H-700N-V',
    category: 'Safety Equipment',
    unit: 'Units',
    referencePrice: 850,
    currency: 'INR',
    description: 'Lightweight safety helmet with 4-point ratchet suspension, ventilation slots, and ANSI/ISEA Z89.1 compliance for workplace protection.',
    specifications: 'Suspension: 4-Point Ratchet | Ventilation: Vented | Certification: IS 2925, ANSI/ISEA Z89.1 Type 1, Class C | Shell: HDPE',
    specificationsObject: {
      'Shell Material': 'High-Density Polyethylene (HDPE)',
      'Suspension Type': 'Smooth 4-Point Ratchet Suspension',
      'Standard Compliance': 'IS 2925 : 1984 & ANSI Z89.1',
      'Features': 'Built-in brow pad, vented crown for airflow',
      'Slot Type': 'Universal accessory slots for earmuffs & faceshields',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Safety White', color: 'White', referencePrice: 850, sku: '3M-H700-WHT' },
      { name: 'Safety Yellow', color: 'Yellow', referencePrice: 850, sku: '3M-H700-YLW' },
      { name: 'Safety Blue', color: 'Blue', referencePrice: 850, sku: '3M-H700-BLU' },
      { name: 'Safety Orange', color: 'Orange', referencePrice: 850, sku: '3M-H700-ORG' },
    ],
    tags: ['3m', 'helmet', 'safety helmet', 'ppe', 'safety equipment', 'hard hat'],
  },
  {
    catalogId: 'MASTER-SAFE-BOOTS-STEELTOE',
    productName: 'Allen Cooper Men Steel Toe Industrial Safety Shoes (ISI Certified)',
    brand: 'Allen Cooper',
    model: 'AC 1156 Hi-Ankle',
    category: 'Safety Equipment',
    unit: 'Pair',
    referencePrice: 2499,
    currency: 'INR',
    description: 'Genuine leather industrial safety shoes with 200J impact steel toe cap, oil & acid resistant PU sole, and anti-static build.',
    specifications: 'Toe Cap: 200 Joules Steel Toe | Sole: Double Density PU | Upper: Genuine Buff Barton Leather | Standards: IS 15298 (Part 2)',
    specificationsObject: {
      'Upper Material': 'Water-resistant genuine breathable leather',
      'Toe Protection': 'Carbon steel toe cap withstanding 200 Joules impact',
      'Sole': 'Double density injected PU sole (slip, oil and fuel resistant)',
      'Electrical Properties': 'Anti-static (100kΩ to 1000MΩ)',
      'Standard': 'ISI marked complying with IS 15298 : Part 2',
      'Warranty': '6 Months Warranty against manufacturing defects',
    },
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Size UK 6', referencePrice: 2499, sku: 'AC-BOOT-06' },
      { name: 'Size UK 7', referencePrice: 2499, sku: 'AC-BOOT-07' },
      { name: 'Size UK 8', referencePrice: 2499, sku: 'AC-BOOT-08' },
      { name: 'Size UK 9', referencePrice: 2499, sku: 'AC-BOOT-09' },
      { name: 'Size UK 10', referencePrice: 2499, sku: 'AC-BOOT-10' },
      { name: 'Size UK 11', referencePrice: 2499, sku: 'AC-BOOT-11' },
    ],
    tags: ['safety shoes', 'safety boots', 'steel toe', 'allen cooper', 'ppe'],
  },
  {
    catalogId: 'MASTER-SAFE-GLOVES-3M-NITRILE',
    productName: '3M Nitrile Safety Work Gloves (Size M, Pack of 10 Pairs)',
    brand: '3M',
    model: 'Comfort Grip CGL-WM',
    category: 'Safety Equipment',
    unit: 'Pack',
    referencePrice: 1200,
    currency: 'INR',
    description: 'Textured nitrile-coated palm gloves for grip in wet and oily conditions. Suitable for general industrial use and mechanical assembly.',
    specifications: 'Material: Nitrile foam coated | Size: Medium | Cut Level: Level A3 | Coating: Full palm + fingertips | Quantity: 10 pairs',
    specificationsObject: {
      'Outer Material': 'Nitrile foam coated palm',
      'Inner Liner': 'Nylon/Spandex knitted liner',
      'Size': 'Medium (fits hand size 7-8)',
      'EN 388 Cut Level': 'Level A3',
      'Application': 'Assembly, general industrial, automotive, landscaping',
      'Quantity': '10 pairs per pack',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Size S - 10 Pairs', referencePrice: 1200, sku: '3M-GLOVE-S-10' },
      { name: 'Size M - 10 Pairs', referencePrice: 1200, sku: '3M-GLOVE-M-10' },
      { name: 'Size L - 10 Pairs', referencePrice: 1200, sku: '3M-GLOVE-L-10' },
    ],
    tags: ['3m', 'gloves', 'nitrile gloves', 'safety gloves', 'ppe'],
  },
  {
    catalogId: 'MASTER-SAFE-GOGGLE-3M-ZB11',
    productName: '3M Zekler 25 Safety Spectacles (Clear Anti-Scratch Lens)',
    brand: '3M',
    model: 'Zekler 25 / GG500',
    category: 'Safety Equipment',
    unit: 'Units',
    referencePrice: 380,
    currency: 'INR',
    description: 'Wraparound safety spectacles with UV-protected polycarbonate lens and anti-scratch coating for industrial and lab use.',
    specifications: 'Lens: Clear Polycarbonate UV400 | Anti-Scratch Coating | Standards: EN 166, ANSI Z87.1 | Frame: Flexible TPE',
    specificationsObject: {
      'Lens Material': 'Polycarbonate (1.5mm)',
      'UV Protection': 'UV400 (blocks 99.9% UVA/UVB)',
      'Coating': 'Anti-scratch / Anti-fog',
      'Frame': 'Flexible TPE lightweight frame',
      'Compliance': 'EN 166:2002, ANSI Z87.1',
      'Weight': 'Approx. 25 g',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Clear Lens', referencePrice: 380, sku: '3M-GOGGLE-CLR' },
      { name: 'Tinted Lens', referencePrice: 420, sku: '3M-GOGGLE-TNT' },
    ],
    tags: ['3m', 'safety glasses', 'safety goggles', 'ppe', 'eye protection'],
  },
  {
    catalogId: 'MASTER-SAFE-JACKET-REFLECTIVE',
    productName: 'Reflective High-Visibility Safety Jacket (Fluorescent Yellow/Orange)',
    brand: '3M / Mallcom',
    model: 'Class 2 Hi-Vis Vest',
    category: 'Safety Equipment',
    unit: 'Units',
    referencePrice: 550,
    currency: 'INR',
    description: 'ANSI Class 2 high-visibility reflective safety vest with 2-inch retroreflective tape stripes and breakaway zipper.',
    specifications: 'Class: ANSI 107 Class 2 | Material: Polyester mesh | Tape: 3M Scotchlite reflective | Closure: Hook & loop / Zip',
    specificationsObject: {
      'Material': '100% Polyester mesh (150 GSM)',
      'Reflective Tape': '3M Scotchlite 50mm retroreflective tape',
      'Visibility Class': 'ANSI/ISEA 107-2015 Class 2',
      'Closure': 'Hook and loop (velcro) or front zip',
      'Sizes Available': 'S, M, L, XL, 2XL, 3XL',
      'Pockets': '2 chest pockets + 1 pen pocket',
      'Compliance': 'EN 471 and IS 15809',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Fluorescent Yellow - Size M', color: 'Yellow', referencePrice: 550, sku: 'HIVIZ-YLW-M' },
      { name: 'Fluorescent Orange - Size M', color: 'Orange', referencePrice: 550, sku: 'HIVIZ-ORG-M' },
      { name: 'Fluorescent Yellow - Size L', color: 'Yellow', referencePrice: 550, sku: 'HIVIZ-YLW-L' },
      { name: 'Fluorescent Yellow - Size XL', color: 'Yellow', referencePrice: 550, sku: 'HIVIZ-YLW-XL' },
    ],
    tags: ['safety jacket', 'reflective jacket', 'high visibility vest', 'ppe', 'safety vest'],
  },
  {
    catalogId: 'MASTER-SAFE-MASK-3M-N95',
    productName: '3M 9002 N95 Particulate Respirator Mask (Box of 50)',
    brand: '3M',
    model: '9002 / 8210',
    category: 'Safety Equipment',
    unit: 'Box',
    referencePrice: 2500,
    currency: 'INR',
    description: 'Disposable N95 respirator masks with adjustable nose clip and foam nose pad for comfortable, secure fit in dusty environments.',
    specifications: 'Protection Level: N95 (95% filtration) | Type: Flat Fold Respirator | Standard: NIOSH N95, IS 9473 | Quantity: 50 per box',
    specificationsObject: {
      'Filtration Efficiency': '95% of airborne particles ≥0.3 microns (N95)',
      'Type': 'Flat-fold disposable respirator',
      'Standard': 'NIOSH N95 / IS 9473 / EN 149 FFP2',
      'Nose Clip': 'Adjustable aluminum nose clip',
      'Exhalation Valve': 'Not included (solid face seal)',
      'Quantity': '50 masks per box',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Box of 50 Masks', referencePrice: 2500, sku: '3M-N95-50PK' },
    ],
    tags: ['3m', 'n95', 'respirator', 'mask', 'safety mask', 'ppe'],
  },
  {
    catalogId: 'MASTER-SAFE-EXTINGUISHER-5KG',
    productName: 'Minimax 5 KG ABC Dry Powder Fire Extinguisher (ISI Marked)',
    brand: 'Minimax',
    model: '5 KG ABC-MAP90',
    category: 'Safety Equipment',
    unit: 'Units',
    referencePrice: 2200,
    currency: 'INR',
    description: 'ISI-marked 5 KG ABC multipurpose dry chemical powder fire extinguisher effective against Class A, B, and C fires.',
    specifications: 'Type: ABC Dry Chemical Powder | Capacity: 5 KG | Agent: MAP 90% | Discharge Time: ~12 sec | Rating: 4A, 34B | Standard: IS 15683',
    specificationsObject: {
      'Type': 'ABC Multi-purpose Dry Chemical Powder',
      'Capacity': '5 KG',
      'Discharge Time': 'Approximately 12 seconds',
      'Fire Rating': '4A, 34B, C',
      'Effective Classes': 'Class A (solid), Class B (liquid), Class C (gas) fires',
      'Standard': 'ISI Marked - IS 15683 / IS 13849',
      'Validity': '10 year body life, annual refilling recommended',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '5 KG ABC Powder', referencePrice: 2200, sku: 'MINIMAX-5KG-ABC' },
      { name: '2 KG ABC Powder', referencePrice: 1500, sku: 'MINIMAX-2KG-ABC' },
    ],
    tags: ['fire extinguisher', 'minimax', 'safety', 'fire safety', 'abc powder'],
  },
  {
    catalogId: 'MASTER-SAFE-FIRSTAID-KIT',
    productName: 'First Aid Kit (50 Person Workplace Industrial Kit)',
    brand: 'Mediaid / SafetyKart',
    model: 'Industrial 50-Person Kit',
    category: 'Safety Equipment',
    unit: 'Units',
    referencePrice: 1800,
    currency: 'INR',
    description: 'Comprehensive workplace first aid kit meeting Factory Act requirements, suitable for 50-person workplaces, in wall-mounted metal box.',
    specifications: 'Persons Covered: 50 | Contents: Bandages, Antiseptic, Scissors, Gauze Pads, Gloves, Eye Wash, CPR mask | Box: Metal wall mount',
    specificationsObject: {
      'Persons Covered': '50 person capacity',
      'Box Material': 'Powder-coated steel wall-mount cabinet',
      'Key Contents': 'Adhesive bandages, sterile gauze, antiseptic wipes, disposable gloves, CPR face shield, scissors, tweezers, eye wash',
      'Compliance': 'Meets Factories Act 1948 First Aid Box Requirement',
      'Refillable': 'Yes',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '50-Person Industrial Kit', referencePrice: 1800, sku: 'FA-KIT-50P' },
    ],
    tags: ['first aid kit', 'medical kit', 'safety equipment', 'workplace safety'],
  },

  // ==========================================
  // INDUSTRIAL EQUIPMENT
  // ==========================================
  {
    catalogId: 'MASTER-IND-BOSCH-GSB120',
    productName: 'Bosch GSB 120-LI Cordless Impact Drill & Driver Kit with 2 Batteries',
    brand: 'Bosch',
    model: 'GSB 120-LI Professional',
    category: 'Industrial Equipment',
    unit: 'Kit',
    referencePrice: 6850,
    currency: 'INR',
    description: 'Professional cordless impact drill for metal, wood, and masonry drilling. Includes 2x 2.0Ah Li-ion batteries, charger, and carrying case.',
    specifications: 'Torque: 30 Nm max | Speed: 0-400 / 0-1500 rpm | Chuck: 1.5-10 mm | Battery: 12V 2.0Ah Li-ion (x2)',
    specificationsObject: {
      'Battery Voltage': '12 V (Includes 2x 2.0 Ah Li-ion batteries)',
      'Torque (Soft/Hard)': '14 / 30 Nm with 20+1 clutch settings',
      'Max Drilling Diameter': 'Wood: 20 mm, Steel: 10 mm, Masonry: 8 mm',
      'Impact Rate': 'Up to 22,500 bpm',
      'Weight': '1.06 kg with battery',
      'Package Includes': 'Drill, 2x Batteries, GAL 1210 CV Charger, Carrying Case',
      'Warranty': '6 Months Bosch India Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Complete 2-Battery Kit', referencePrice: 6850, sku: 'BOSCH-GSB120-KIT' },
    ],
    tags: ['bosch', 'drill', 'cordless drill', 'industrial equipment', 'tools', 'power tools'],
  },
  {
    catalogId: 'MASTER-IND-FLUKE-101',
    productName: 'Fluke 101 Digital Multimeter (Pocket Portable Basic TRMS)',
    brand: 'Fluke',
    model: 'Fluke 101',
    category: 'Industrial Equipment',
    unit: 'Units',
    referencePrice: 3890,
    currency: 'INR',
    description: 'Accurate pocket-sized industrial digital multimeter for basic electrical tests, CAT III 600V safety rating, auto-ranging.',
    specifications: 'Safety: CAT III 600V | Voltage AC/DC: Up to 600V | Resistance: Up to 40 MΩ | Capacitance: Up to 100 μF',
    specificationsObject: {
      'AC/DC Voltage Range': '600.0 V (0.5% basic DC accuracy)',
      'Resistance Range': '400.0 Ω to 40.00 MΩ',
      'Capacitance Range': '50.00 nF to 100.0 μF',
      'Safety Rating': 'CAT III 600 V compliant with IEC 61010-1',
      'Display': '6000 count digital LCD display',
      'Battery': '2x AAA Alkaline batteries (approx. 200 hours)',
      'Warranty': '1 Year Fluke Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard Multimeter', referencePrice: 3890, sku: 'FLUKE-101' },
    ],
    tags: ['fluke', 'multimeter', 'industrial equipment', 'electrical', 'testing tools'],
  },
  {
    catalogId: 'MASTER-IND-MAKITA-M0800B',
    productName: 'Makita M0800B 800W Angle Grinder (125mm / 5-inch)',
    brand: 'Makita',
    model: 'M0800B',
    category: 'Industrial Equipment',
    unit: 'Units',
    referencePrice: 3290,
    currency: 'INR',
    description: 'Reliable 800W corded angle grinder for grinding, cutting, and polishing metal with ergonomic barrel grip and slim-body design.',
    specifications: 'Power: 800W | Disc Size: 125mm (5") | No-Load Speed: 11,000 RPM | Spindle: M14 | Weight: 1.7 kg',
    specificationsObject: {
      'Input Power': '800 W',
      'Disc Diameter': '125 mm (5 inch)',
      'No-Load Speed': '11,000 RPM',
      'Spindle Thread': 'M14',
      'Wheel Guard': 'Adjustable safety guard',
      'Switch': 'Paddle switch with lock-off button',
      'Weight': '1.7 kg',
      'Warranty': '1 Year Makita India Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Standard 125mm', referencePrice: 3290, sku: 'MAKITA-M0800B' },
    ],
    tags: ['makita', 'angle grinder', 'grinder', 'industrial equipment', 'power tools'],
  },
  {
    catalogId: 'MASTER-IND-COMPRESSOR-ELGI-7CFM',
    productName: 'Elgi AB007-110/6 1 HP Oil-Lubricated Air Compressor (7 CFM, 6 Bar)',
    brand: 'Elgi',
    model: 'AB007-110/6',
    category: 'Industrial Equipment',
    unit: 'Units',
    referencePrice: 18500,
    currency: 'INR',
    description: 'Reliable 1 HP oil-lubricated reciprocating air compressor for spray painting, inflation, and pneumatic tools in workshops.',
    specifications: 'Power: 1 HP (750W) | FAD: 7 CFM (200 LPM) | Pressure: 6 bar (87 PSI) | Tank: 24 litres | Motor: 1Ph 230V',
    specificationsObject: {
      'Motor Power': '1 HP (750 W) Single Phase 230V',
      'Free Air Delivery (FAD)': '7 CFM (200 LPM)',
      'Maximum Pressure': '6 Bar (87 PSI)',
      'Tank Capacity': '24 Litres',
      'Type': 'Oil-lubricated reciprocating single-stage',
      'Noise Level': 'Approx. 80 dB',
      'Weight': '35 kg',
      'Warranty': '1 Year Elgi Compressors Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '1 HP / 24L Tank', referencePrice: 18500, sku: 'ELGI-AB007-6BAR' },
    ],
    tags: ['elgi', 'air compressor', 'compressor', 'industrial equipment', 'pneumatic'],
  },
  {
    catalogId: 'MASTER-IND-MEASURING-TAPE-30M',
    productName: 'Stanley FatMax 30M Tape Measure (Magnetic Hook)',
    brand: 'Stanley',
    model: 'FatMax 30M',
    category: 'Industrial Equipment',
    unit: 'Units',
    referencePrice: 1850,
    currency: 'INR',
    description: 'Long-reach 30-metre steel tape measure with BladeArmor coating, magnetic hook, and easy-lock button for accurate site measurement.',
    specifications: 'Length: 30 metres | Width: 12.7mm | Blade: Steel with BladeArmor | Magnetic Hook | Lock: Easy button | Case: ABS rubber grip',
    specificationsObject: {
      'Tape Length': '30 metres (100 feet)',
      'Tape Width': '12.7 mm (1/2 inch)',
      'Blade Material': 'Steel with BladeArmor™ polyester coating',
      'Accuracy Class': 'Class II (EN ISO 13225)',
      'Hook': 'Magnetic end hook for one-person measurements',
      'Case': 'ABS rubber over-mould',
      'Warranty': '1 Year Warranty',
    },
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '30 Metre', referencePrice: 1850, sku: 'STANLEY-TAPE-30M' },
      { name: '5 Metre', referencePrice: 650, sku: 'STANLEY-TAPE-5M' },
    ],
    tags: ['stanley', 'tape measure', 'measuring tape', 'tools', 'industrial equipment'],
  },

  // ==========================================
  // SOFTWARE - LICENSES & CLOUD SUBSCRIPTIONS
  // ==========================================
  {
    catalogId: 'MASTER-SOFT-M365-BUS-STD',
    productName: 'Microsoft 365 Business Standard (1-Year Subscription / 1 User)',
    brand: 'Microsoft',
    model: 'Business Standard ESD',
    category: 'Software',
    unit: 'License',
    referencePrice: 11200,
    currency: 'INR',
    description: 'Commercial cloud suite including desktop Word, Excel, PowerPoint, Outlook, Microsoft Teams, and 1TB OneDrive per user.',
    specifications: 'Validity: 1 Year | Users: 1 User (5 PCs + 5 Phones + 5 Tablets) | Cloud: 1TB OneDrive + Exchange 50GB',
    specificationsObject: {
      'Subscription Term': '12 Months (1 Year)',
      'Installed Apps': 'Word, Excel, PowerPoint, Outlook, Access (PC only), Publisher (PC only)',
      'Cloud Services': 'Microsoft Teams, Exchange Online, OneDrive for Business (1 TB), SharePoint',
      'Installations': 'Up to 5 PCs/Macs, 5 tablets, and 5 mobile devices',
      'Email Hosting': '50 GB business-class mailbox',
      'License Type': 'Commercial Enterprise ESD',
    },
    imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '1-User 1-Year Subscription', referencePrice: 11200, sku: 'MS-365-BUS-1Y' },
    ],
    tags: ['microsoft', 'office', 'm365', 'software', 'license', 'cloud', 'teams'],
  },
  {
    catalogId: 'MASTER-SOFT-WIN11-PRO',
    productName: 'Microsoft Windows 11 Pro 64-Bit OEM / Retail Digital License',
    brand: 'Microsoft',
    model: 'Windows 11 Professional',
    category: 'Software',
    unit: 'License',
    referencePrice: 13500,
    currency: 'INR',
    description: 'Lifetime professional OS license with BitLocker, Remote Desktop, Hyper-V, and enterprise-grade management features.',
    specifications: 'License: Lifetime 1 PC | Architecture: 64-Bit | Key Features: BitLocker, Hyper-V, Windows Sandbox, Remote Desktop Server',
    specificationsObject: {
      'License Type': 'Commercial Single Device Perpetual License',
      'Architecture': '64-Bit Native',
      'Security Features': 'BitLocker Drive Encryption, Windows Defender, TPM 2.0 Required',
      'Virtualization': 'Client Hyper-V, Windows Sandbox',
      'Remote Desktop': 'Full Remote Desktop Host and Client functionality',
    },
    imageUrl: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '1 PC Lifetime Retail', referencePrice: 13500, sku: 'WIN11-PRO-DIGITAL' },
    ],
    tags: ['windows 11', 'microsoft', 'os', 'operating system', 'software', 'license'],
  },
  {
    catalogId: 'MASTER-SOFT-ADOBE-ACROBAT-PRO',
    productName: 'Adobe Acrobat Pro (Annual Subscription / 1 User)',
    brand: 'Adobe',
    model: 'Acrobat Pro - Annual Plan',
    category: 'Software',
    unit: 'License',
    referencePrice: 20690,
    currency: 'INR',
    description: 'Complete PDF solution for creating, editing, signing, and sharing PDFs. Includes AI-powered tools and cloud storage.',
    specifications: 'Validity: 1 Year Subscription | Users: 1 User | Features: PDF Create, Edit, Sign, Compare, Convert | Cloud: 100GB Adobe Storage',
    specificationsObject: {
      'Subscription Term': '12 Months Annual',
      'Platforms': 'Windows, macOS, iOS, Android, Web Browser',
      'Core Features': 'Create, edit, sign, OCR, compare PDFs, form filling, digital signatures',
      'Cloud Storage': '100 GB Adobe Cloud',
      'AI Features': 'AI-powered document redaction and summarization',
      'License Type': 'Individual Named User License',
    },
    imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '1-User Annual Subscription', referencePrice: 20690, sku: 'ADOBE-ACROBAT-PRO-1Y' },
    ],
    tags: ['adobe', 'acrobat', 'pdf', 'software', 'subscription', 'digital signature'],
  },
  {
    catalogId: 'MASTER-SOFT-KASPERSKY-3PC',
    productName: 'Kaspersky Total Security (3 PC / 1 Year License)',
    brand: 'Kaspersky',
    model: 'Total Security 3PC',
    category: 'Software',
    unit: 'License',
    referencePrice: 1299,
    currency: 'INR',
    description: 'Comprehensive endpoint security with anti-virus, anti-phishing, parental controls, VPN, password manager, and privacy tools for 3 PCs.',
    specifications: 'Devices: 3 PCs | Validity: 1 Year | Features: Antivirus, Anti-phishing, VPN, Password Manager, Parental Controls',
    specificationsObject: {
      'Device Coverage': '3 Devices (PC/Mac/Mobile)',
      'Subscription Term': '12 Months',
      'Core Security': 'Real-time antivirus, Anti-ransomware, Behavior Detection',
      'Privacy Tools': 'VPN, Webcam & Mic protection, Password Manager',
      'Additional': 'Parental Controls, Safe Banking, Vulnerability Scanner',
    },
    imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '3 PC / 1 Year', referencePrice: 1299, sku: 'KSKY-TS-3PC-1Y' },
      { name: '5 PC / 1 Year', referencePrice: 1699, sku: 'KSKY-TS-5PC-1Y' },
    ],
    tags: ['kaspersky', 'antivirus', 'security software', 'endpoint security', 'license'],
  },
  {
    catalogId: 'MASTER-SOFT-TALLY-PRIME',
    productName: 'TallyPrime 4.0 Silver Edition (Single User License)',
    brand: 'Tally Solutions',
    model: 'TallyPrime Silver',
    category: 'Software',
    unit: 'License',
    referencePrice: 22500,
    currency: 'INR',
    description: 'Industry-standard Indian business management software for GST-compliant accounting, inventory, banking, payroll, and compliance.',
    specifications: 'Edition: Silver (1 simultaneous user) | Features: GST, TDS, Payroll, Inventory, Banking | Subscription: Annual TSS recommended',
    specificationsObject: {
      'Edition': 'Silver (1 concurrent user)',
      'License Type': 'Perpetual License (Annual TSS recommended for updates)',
      'GST': 'GST invoicing, returns, e-Way Bill, e-Invoice',
      'Accounting': 'Voucher entry, P&L, Balance Sheet, Cash/Fund Flow',
      'Inventory': 'Multi-godown, batch, expiry, multi-currency',
      'Payroll': 'PF, ESI, PT, TDS, Salary Processing',
    },
    imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: 'Silver - 1 User', referencePrice: 22500, sku: 'TALLY-PRIME-SILVER' },
      { name: 'Gold - Unlimited Users', referencePrice: 67500, sku: 'TALLY-PRIME-GOLD' },
    ],
    tags: ['tally', 'tally prime', 'accounting software', 'gst software', 'erp'],
  },
  {
    catalogId: 'MASTER-SOFT-ZOOM-PRO-1Y',
    productName: 'Zoom Pro Plan (Annual Subscription / 1 Host License)',
    brand: 'Zoom',
    model: 'Pro Plan - Annual',
    category: 'Software',
    unit: 'License',
    referencePrice: 13200,
    currency: 'INR',
    description: 'Professional video conferencing subscription with unlimited 30-hour meetings, 5GB cloud recording, and admin controls for 1 host.',
    specifications: 'Hosts: 1 | Meeting Duration: Up to 30 hours | Participants: Up to 100 | Cloud Recording: 5 GB | Validity: 12 Months',
    specificationsObject: {
      'Meeting Duration': 'Up to 30 hours per meeting',
      'Maximum Participants': 'Up to 100 per meeting',
      'Cloud Recording': '5 GB per license',
      'Admin Features': 'User management, Meeting scheduling, Reporting',
      'License Term': '1 Year Annual Subscription',
      'Platforms': 'Windows, macOS, iOS, Android, Web',
    },
    imageUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    imageSource: 'catalog',
    variants: [
      { name: '1 Host / Annual Subscription', referencePrice: 13200, sku: 'ZOOM-PRO-1H-1Y' },
    ],
    tags: ['zoom', 'video conferencing', 'software', 'cloud software', 'collaboration'],
  },
];

module.exports = {
  masterCatalogProducts,
};
